### ISSUE TITLE
Creating Routes for Services 

### ISSUE THREAD

**Issue by kadel** [kubernetes-incubator/kompose#140]
OpenShift can expose Services using Routes.

It would be nice if Kompose created default Routes for some services.

User can specify for which services Route should be created for example like this:

```
kompose convert --expose-service=<service name>
```

cc: @kbsingh

**Comment by runseb** [comment]
@kadel sounds good. Only issue will be how to handle this for multiple providers.

i.e for vanilla Kubernetes what will the behavior of this expose-service option ?

If we implement a --provider we could start adding provider specific options...

**Comment by kadel** [comment]
k8s version of route would be Ingress object

**Comment by dustymabe** [comment]
I still like the idea of using labels to express some of this behavior rather than adding a ton of CLI options.

**Comment by kadel** [comment]
This could be solved in similar way as https://github.com/skippbox/kompose/issues/154

We decided that we are going to use labels to provide additional information for conversion.

for example label for this could be `<kompose_namespace>.service.expose: foo.bar.example.com`
value  can be also  empty and it would mean that dns name should be constructed automatically by OpenShift.

For Kubernetes same thing should be done, but it will create Ingress object instead of Route.

**Comment by kbsingh** [comment]
sounds good, and would resolve this issue for me.

**Comment by dustymabe** [comment]
I believe @containscafeine has volunteered to work on this in the next few weeks. can you assign him on this ?

**Comment by dustymabe** [comment]
@containscafeine any progress on this?

**Comment by containscafeine** [comment]
@dustymabe I've been trying to implement the route API from `openshift/origin/pkg/route/api` but hitting some issues. I will be away for some time, so I'm updating @surajssd about my progress just in case.

**Comment by kadel** [comment]
@containscafeine @surajssd If you hit any bumps just ping me I'm happy to help.
