### ISSUE TITLE
integration with minikube/minishift

### ISSUE THREAD

**Issue by dustymabe** [kubernetes-incubator/kompose#156]
It would be nice to somehow add some support for a "local" use case where a user doesn't yet have k8s running. We don't want the scope of Kompose to creep too much but it would be interesting to be able to integrate with some other tools to help bring up a cluster and actually bring up the app.

an example would be:

```
$ kompose up
We are going to create Kubernetes deployments and services for your Dockerized application. 
If you need different kind of resources, use the 'kompose convert' and 'kubectl create -f' commands instead. 

--> We see you don't have a kube environment configured in ~/.kube/config, but minikube is installed. 
--> Would you like us to bring up a local cluster? (y/n) y
--> Bringing up local k8s cluster using minikube.....
--> Cluster up

INFO[0000] Successfully created service: web            
INFO[0000] Successfully created service: redis          
INFO[0000] Successfully created deployment: web         
INFO[0000] Successfully created deployment: redis       

Your application has been deployed to Kubernetes. You can run 'kubectl get deployment,svc,pods' for details.
```

**Comment by runseb** [comment]
I haven't checked if we have this already, but I'd rather have a warning that says "no k8s cluster available, bring one up..."

**Comment by ngtuna** [comment]
> We don't want the scope of Kompose to creep too much but it would be interesting to be able to integrate with some other tools to help bring up a cluster and actually bring up the app.

Could I say kmachine ?

**Comment by sebgoa** [comment]
Sadly with minikube, kmachine is "obsolete". If we do this, minikube is the choice.

**Comment by sebgoa** [comment]
@cab105 another for you :)

kompose reads the k8s config file and targets the default context. We need to check a few things:

1-what happens if there is no default context ? Maybe offer the use the choice of setting the context based on the ones in the config file.
2-What happens if the default context is actually not running/available ?
3-if there is a minikube context, then check if it is running, if not start it and use that.

**Comment by cab105** [comment]
@sebgoa Have been meaning to spend more time with minikube.  Added to the list.

**Comment by cab105** [comment]
@sebgoa What I'm thinking about implementing is a new provider on par with openshift that the user could call by default, and the provide the appropriate check with kubernetes, where if the default path fails, then fallback to Minikube if it's installed.

**Comment by sebgoa** [comment]
yes, that's a good idea.

**Comment by cab105** [comment]
Okay opted to go with the original approach of attempting to load via the default kubernetes context, and if that fails, then try to find minikube, prompt and use that to bring up the instance.  This way if the default context also happens to be minikube, and its not running, we'll still prompt before firing up minikube.

Now the next question is when we want to do `kompose down` and we happen to be in a minikube context, do we prompt to bring minikube down as well?

**Comment by ericchiang** [comment]
This seems like an odd feature to add and in my opinion it detracts from the goals of the project. This is going to be a nightmare supporting various configuration options, and kompose shouldn't be a tool for bringing up clusters. Such tools are incredibly hard to maintain and don't relate to converting compose files to kubernetes objects.

I'd strongly recommend just writing documentation like the following instead:

```
# Getting started

The easiest way to kick the tires on kompose is to use minikube to start a local Kubernetes instance, then run your compose.

minikube start
// use kompose
```

I think that kind of documentation saves you a ton of time and effort trying to maintain such a feature, and let's kompose focus on doing one thing well.

**Comment by cab105** [comment]
@ericchiang You do raise a good point, and this is something that could be better addressed via documentation.  @sebgoa would this approach work out better instead?

**Comment by surajssd** [comment]
This is a feature creep! Let people using kompose take care of bringing up a cluster, kompose should not do it.

**Comment by kadel** [comment]
I agree that this should be solved by documentation. For example we could write some kind of tutorial - Kompose 101 that will cover using minikube with kompose.

**Comment by sebgoa** [comment]
we are all in agreement then, it does look like kompose trying to do too much.
I am closing the issue and the pr. thanks @cab105 for proposing a solution though.
