### ISSUE TITLE
Add tests converting dab files

### ISSUE THREAD

**Issue by kadel** [kubernetes-incubator/kompose#167]
there is no test in [test.sh](https://github.com/skippbox/kompose/blob/master/script/test/cmd/tests.sh) that converts dab file.

**Comment by sebgoa** [comment]
cc/ @cab105 that's another easy one for you.

We need some fixtures and modifications to test.sh to run the conversion of docker bundles

```
kompose --bundle docker-compose.dab convert
```

**Comment by cab105** [comment]
@sebgoa Sure, I'll take a look at it this weekend.

**Comment by cab105** [comment]
Modifications to test.sh and lib.sh to support multiple output files.

**Comment by ngtuna** [comment]
Can we close this issue ?

**Comment by cab105** [comment]
Not yet, I have another changeset that addresses this.  Will also need to open up another issue to account for the failed test.
