### ISSUE TITLE
Fixtures directory has README.md that are incomplete or inconsistent

### ISSUE THREAD

**Issue by surajssd** [kubernetes-incubator/kompose#177]
The test scripts from fixtures has README.md which has info of how to run those examples with `docker-compose` we can add info of using it with `kompose`.
- https://github.com/skippbox/kompose/tree/master/script/test/fixtures/etherpad
- https://github.com/skippbox/kompose/tree/master/script/test/fixtures/gitlab
- https://github.com/skippbox/kompose/tree/master/script/test/fixtures/ngnix-node-redis

These fixtures directories have no README.md at all.
- https://github.com/skippbox/kompose/tree/master/script/test/fixtures/entrypoint-command
- https://github.com/skippbox/kompose/tree/master/script/test/fixtures/ports-with-proto

**Comment by kadel** [comment]
Is it necessary for test fixtures to have README?
entrypoint-commmand and ports-with-proto are not even meaningful applications

**Comment by surajssd** [comment]
I just wanted to make sure that these apps work when deployed so that end-to-end still works when we do `kompose up` on them!

**Comment by sebgoa** [comment]
@surajssd I hear you..*but* some of these docker-compose files will most likely break at some point.  The ether pad one for example uses a mariad db container without an image tag...so latest might change underneath you at some point.

+ image tags are not immutable anyway.

So technically we should actually verify that the docker-compose files actually give a working app...

**Comment by surajssd** [comment]
i don't think this is required/valid so closing it.
