### ISSUE TITLE
Documentation site

### ISSUE THREAD

**Issue by cdrage** [kubernetes-incubator/kompose#185]
Hey all,

In preparation for Kubecon next month, I'd like to add a documentation site for people to browse for easier viewing.

An outside contributor helped me recently created this via `Sphinx` documentation generation https://cdrage.github.io/kubeshift/

Which can be configured to either manually be generated each-time you want to update the site, or updated on each push to master via travis-ci.

Would this be something that skippbox is interested in?

The documentation would be generated to a `gh-pages` branch within this repo. It would be available @ https://skippbox.github.io/kompose

**Comment by sebgoa** [comment]
@cdrage sure we can do this.

**Comment by sebgoa** [comment]
I have created the gh-pages branch

**Comment by cdrage** [comment]
@sebgoa Awesome! I'll work on it this week and get a PR up and running :)

**Comment by cdrage** [comment]
Closing this for now since this documentation could perhaps be pushed to the kubernetes.io site instead.
