### ISSUE TITLE
establish release process - protect master branch

### ISSUE THREAD

**Issue by dustymabe** [kubernetes-incubator/kompose#192]
Hey hey!

I went to create the new rpm today for kompose 0.1.1 and see that the history is lost for the tag 0.1.1 from the master branch. According to the [release page](https://github.com/skippbox/kompose/releases/tag/v0.1.1) it was tagged from 534fa9b but that commit does not show up in the history for the master branch. I believe that means that the master branch was force pushed to in order to overwrite history. 

Can we possibly do the following: 
- establish a methodical release process to follow for a release
- protect the master branch from any force pushes ever (you can configure this in the settings in github so that it protects history from getting lost)
- always do work through pull requests and require at least one maintainer +1 before doing a merge

**Comment by ngtuna** [comment]
Yes @dustymabe that was a mistake then I made a force push on https://github.com/skippbox/kompose/commit/534fa9ba1d46909ffb20004dbc75bc9bcc7eae2c.

> establish a methodical release process to follow for a release

Yes. I believe @sebgoa is working on it.

> protect the master branch from any force pushes ever (you can configure this in the settings in github so that it protects history from getting lost)

Done. I disabled force push on master and required to have one approved review prior to the PR is getting merged.

> always do work through pull requests and require at least one maintainer +1 before doing a merge

We are having this procedure.

**Comment by dustymabe** [comment]
@ngtuna thanks! I guess once @sebgoa gets the docs for the release process published then we can close this issue.

for the record i think I'll wait for 0.1.2 to update the downstream rpm.

**Comment by sebgoa** [comment]
closing this for #70
