### ISSUE TITLE
error on extraneous/unexpected cli input

### ISSUE THREAD

**Issue by dustymabe** [kubernetes-incubator/kompose#193]
we should probably error out if we get extra arguments/input on the CLI that we don't expect or understand. One example of this is when I was trying to start the gitlab example but I was doing it wrong:

```
[vagrant@f24 examples (upstreammaster=)]$ ../kompose --version
kompose version 0.1.1 (5a37bf0)
[vagrant@f24 examples (upstreammaster=)]$ ../kompose up docker-gitlab.yml 
We are going to create Kubernetes deployments and services for your Dockerized application. 
If you need different kind of resources, use the 'kompose convert' and 'kubectl create -f' commands instead. 

INFO[0000] Successfully created service: web            
INFO[0000] Successfully created service: redis          
INFO[0000] Successfully created deployment: web         
INFO[0000] Successfully created deployment: redis       

Your application has been deployed to Kubernetes. You can run 'kubectl get deployment,svc,pods' for details.
```

So you can see I was trying to run gitlab, but I didn't specify things like I should have: `kompose -f docker-gitlab.yml up`. This means that it actually ignored the `docker-gitlab.yml` that I passed on the command line and used the default `docker-compose.yml` instead and it looks like the application is brought up (if you aren't paying attention too close). 

Now if instead it would error out when it detected extraneous input then I would have found out what was wrong sooner than later.

**Comment by procrypt** [comment]
@dustymabe can I work on it, if no one else working on it.

**Comment by sebgoa** [comment]
@procrypt just assigned it to you.

**Comment by procrypt** [comment]
@sebgoa Thanks :)
