### ISSUE TITLE
wrong global --bundle/--dab input

### ISSUE THREAD

**Issue by ngtuna** [kubernetes-incubator/kompose#198]
```console
$ kompose --bundle docker-voting-bundle.dsb convert
FATA[0000] Error: 'compose' file and 'dab' file cannot be specified at the same time
```

Figured out `opt.InputFile` received `docker-voting-bundle.dsb` instead of `docker-compose.yml` then the [if clause](https://github.com/ngtuna/kompose/blob/master/cli/app/app.go#L74) returned true.

**Comment by cab105** [comment]
@ngtuna I have a fix for this along with my initial test.sh work for #167.

**Comment by ngtuna** [comment]
close via #221
