### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by beravelli** [kubernetes-incubator/kompose#202]
I am facing this issue when converting the docker-compose.yml file . It is a straighforward compose file with couple of volume mounts and no env variables.

Kompose version : kompose version 0.1.0 (8227684)
Error:
------
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x18 pc=0xbbff5c]

goroutine 1 [running]:
panic(0x15a9b60, 0xc82000e0e0)
        /usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/skippbox/kompose/vendor/github.com/docker/libcompose/project.(*Project).handleNetworkConfig(0xc8201762a0)
        /home/tuna/workspace/gocode-kompose/src/github.com/skippbox/kompose/vendor/github.com/docker/libcompose/project/project.go:254 +0x26c
github.com/skippbox/kompose/vendor/github.com/docker/libcompose/project.(*Project).load(0xc8201762a0, 0xc820355c40, 0x12, 0xc8201e4800, 0x4c3, 0x6c3, 0x0, 0x0)
        /home/tuna/workspace/gocode-kompose/src/github.com/skippbox/kompose/vendor/github.com/docker/libcompose/project/project.go:209 +0x638
github.com/skippbox/kompose/vendor/github.com/docker/libcompose/project.(*Project).Parse(0xc8201762a0, 0x0, 0x0)
        /home/tuna/workspace/gocode-kompose/src/github.com/skippbox/kompose/vendor/github.com/docker/libcompose/project/project.go:87 +0x335
github.com/skippbox/kompose/pkg/loader/compose.(*Compose).LoadFile(0x22db590, 0xc820355c40, 0x12, 0x0)
        /home/tuna/workspace/gocode-kompose/src/github.com/skippbox/kompose/pkg/loader/compose/compose.go:121 +0x52f
github.com/skippbox/kompose/cli/app.Convert(0xc8202e1400)
        /home/tuna/workspace/gocode-kompose/src/github.com/skippbox/kompose/cli/app/app.go:145 +0x4e8
github.com/skippbox/kompose/cli/command.ConvertCommand.func1(0xc8202e1400)
        /home/tuna/workspace/gocode-kompose/src/github.com/skippbox/kompose/cli/command/command.go:32 +0x21
github.com/skippbox/kompose/vendor/github.com/urfave/cli.Command.Run(0x1811338, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc8203947d0, 0x4b, 0x0, ...)
        /home/tuna/workspace/gocode-kompose/src/github.com/skippbox/kompose/vendor/github.com/urfave/cli/command.go:179 +0x1399
github.com/skippbox/kompose/vendor/github.com/urfave/cli.(*App).Run(0xc8203c2840, 0xc82000a140, 0x4, 0x4, 0x0, 0x0)
        /home/tuna/workspace/gocode-kompose/src/github.com/skippbox/kompose/vendor/github.com/urfave/cli/app.go:196 +0x137c
main.main()
        /home/tuna/workspace/gocode-kompose/src/github.com/skippbox/kompose/cli/main/main.go:47 +0x33b

**Comment by kadel** [comment]
Hi @beravelli 
from trace you posted it looks like issue with libcompose, during parsing network definition. 

Can you please show docker-compose file that you used, or at least snippet of it with network definitions?

**Comment by beravelli** [comment]
Hi kadel,

networks:
           - incubator

networks:
  incubator:

**Comment by beravelli** [comment]
It works it I take out the networks and volumes section in the docker-compose.yml file

**Comment by ngtuna** [comment]
@beravelli network definition was improved with this recent PR https://github.com/skippbox/kompose/pull/195. We will soon publish new release included this fix. Right now could you try getting kompose HEAD and test with your compose file?

**Comment by ngtuna** [comment]
Similar issue: https://github.com/skippbox/kompose/issues/149

**Comment by ngtuna** [comment]
close via #195
