### ISSUE TITLE
compose constructs we support are still there in unsupportedKey

### ISSUE THREAD

**Issue by surajssd** [kubernetes-incubator/kompose#207]
We do support things like `CPUSet`, `CPUShares`, etc. as seen in code [here](https://github.com/skippbox/kompose/blob/master/pkg/loader/compose/compose.go#L187) but we still have them in [`unsupportedKey` map](https://github.com/skippbox/kompose/blob/master/pkg/kobject/kobject.go#L29). So this is inconsistency, which should be fixed.

**Comment by ngtuna** [comment]
Right. Unsupported keys hasn't been tracked for a while.
