### ISSUE TITLE
being able to store artifacts separately in a specific directory

### ISSUE THREAD

**Issue by containscafeine** [kubernetes-incubator/kompose#209]
Hi,

It would be great if I could store the generated provider artifacts to a specific directory other than the current working directory without having to bundling them into a single file (which `kompose convert -o ...`  currently does.

So, when `kompose convert -o artifacts` is run, if `artifacts` is a directory, then kompose should store all the resulting files inside it, and if it's not, then it should store the artifacts in a single file.

Thoughts?

**Comment by pradeepto** [comment]
I totally could use this bit. @surajssd  and I were discussing earlier this week about exactly this.

**Comment by dustymabe** [comment]
I think this makes sense +1 from me.

**Comment by procrypt** [comment]
@containscafeine I would like to work on it, if no one else is working on it.

**Comment by sebgoa** [comment]
@procrypt I just assigned this to you and put it for v0.3 release.

this has been requested at least by one user.

**Comment by procrypt** [comment]
Hey @sebgoa, I think @containscafeine is already working on the issue.
