### ISSUE TITLE
PVCs are not created when calling `kompose up`

### ISSUE THREAD

**Issue by kadel** [kubernetes-incubator/kompose#218]

**Comment by surajssd** [comment]
Yes I think this is because there is no case for creating a PVC here https://github.com/kubernetes-incubator/kompose/blob/master/pkg/transformer/kubernetes/kubernetes.go#L357

**Comment by kadel** [comment]
@surajssd yes this is the reason for this, and same think in `openshift.go`

**Comment by kadel** [comment]
this breaks kompose for docker-compose files that are using volumes so I'm giving this P0
