### ISSUE TITLE
Switch slack channel to official kubernetes slack

### ISSUE THREAD

**Issue by ericchiang** [kubernetes-incubator/kompose#222]

**Comment by sebgoa** [comment]
yes, we need to get a #kompose channel created in k8s slack then switch over.

**Comment by ericchiang** [comment]
@sebgoa thanks updated the issue. I'll ask around and see who can make this happen.

**Comment by sebgoa** [comment]
maybe if we just ping @sarahnovotny she will create a #kompose channel for us on k8s slack ?

**Comment by sarahnovotny** [comment]
done.

(after a brief foray on the wrong slack)
