### ISSUE TITLE
Switch Copyright

### ISSUE THREAD

**Issue by sebgoa** [kubernetes-incubator/kompose#223]
Currently still with Skippbox, I am checking a few things with CNCF to see if we move to "Kubernetes Authors"

**Comment by sebgoa** [comment]
I am working on this, I just need a green light. should be coming quickly.

**Comment by sebgoa** [comment]
@sarahnovotny Hi, could you confirm that we can switch the copyright to "The Kubernetes Authors" and not to "Cloud Native Computing Foundation" even though the software was donated to CNCF in the skippbox CCLA.

**Comment by sarahnovotny** [comment]
ack "The Kubernetes Authors" for consistency sake.
