### ISSUE TITLE
provide easy option for users in setup without PVs

### ISSUE THREAD

**Issue by dustymabe** [kubernetes-incubator/kompose#226]
If a user is targeting an env without PVs it would be great if we gave them an easy option for getting up and running. Rather than having them create PVs (which can be complicated or maybe even not allowed if they don't control their environment) I think we should give them the option `--volume=empty`  to substitute in a `emptyDir` for a PVC. The --volume option would could default to `--volume=pvc`. 

This would allow them to get going without having to have it all set up, but would keep sane defaults for people who have real environments with appropriate volume setups. 

More information on `emptyDir` [here](http://kubernetes.io/docs/user-guide/volumes/#emptydir)

**Comment by dustymabe** [comment]
alternatively we could default to `emptyDir` and warn the user that if they want persistence they should provide `--volume=pvc`.

**Comment by dustymabe** [comment]
This is another thing that we might want to put in a preference file as well.

**Comment by kadel** [comment]
This is great idea. But I would keep `--volume=pvc` as default, because I  think that `emptyDir` is dangerous for users that don't know what it does.
