### ISSUE TITLE
Invoking kompose --bundle X.dab convert --stdout will produce two differently ordered results

### ISSUE THREAD

**Issue by cab105** [kubernetes-incubator/kompose#231]
The current kompose testing framework relies on dumping the results of the command to stdout and comparing it against a known baseline.  While doing the same thing for converting bundles, kompose will alter the order of the output such that no two invocations will result in the same output (see test1.txt and test2.txt).

While this doesn't pose an issue for normal operations, this will result in the tests failing occasionally.  The primary question is whether the tests should be altered to compare the resulting file output, or of dumping via stdout should be consistent?

[test1.txt](https://github.com/kubernetes-incubator/kompose/files/545981/test1.txt)
[test2.txt](https://github.com/kubernetes-incubator/kompose/files/545982/test2.txt)

**Comment by surajssd** [comment]
@cab105 see if this helps https://github.com/kubernetes-incubator/kompose/blob/master/script/test/cmd/lib.sh#L70 

It can match json even if the order changes. Also you can use functions like `convert::match_output` directly.

**Comment by surajssd** [comment]
@cab105 see the usage here https://github.com/kubernetes-incubator/kompose/blob/master/script/test/cmd/tests.sh#L15

**Comment by cab105** [comment]
Thanks for the guideline, but the thing is that I'm running this through 
convert::expect_success and convert::expect_success_and_warning so 
convert::match_output is being called.

Then again, I need to debug if this is my environment or a bug with the 
test scripts.

**Comment by sebgoa** [comment]
@cab105 can we close this ?

**Comment by cab105** [comment]
I'd say not yet.  Haven't had a chance to delve into it, but will take ownership.

**Comment by cdrage** [comment]
https://github.com/kubernetes-incubator/kompose/pull/338 has been merged. This is safe to be closed.
