### ISSUE TITLE
Raw Pod output

### ISSUE THREAD

**Issue by sstarcher** [kubernetes-incubator/kompose#234]
Feature request for supporting the output of a raw Pod definition.

**Comment by dustymabe** [comment]
can you elaborate a little more on what exactly you want?

**Comment by sstarcher** [comment]
Kompose currently supports

```
  --chart, -c				Create a Helm chart for converted objects
   --deployment, -d			Generate a Kubernetes deployment object (default on)
   --daemonset, --ds			Generate a Kubernetes daemonset object
   --replicationcontroller, --rc	Generate a Kubernetes replication controller object
```

The request is for a --pod that will output a pod definition without any controller.

```
kind: Pod
```

**Comment by sebgoa** [comment]
@ngtuna that one should be pretty straightforward

**Comment by kadel** [comment]
this could be solved with `restart:no` if implement as discussed  in https://github.com/kubernetes-incubator/kompose/issues/236

**Comment by sebgoa** [comment]
@sstarcher you want all docker services to be in a Single Pod, or a Pod per docker services ?

**Comment by sstarcher** [comment]
I would say all in one pod would be preferable.

**Comment by ericchiang** [comment]
Is this for constructing your own jobs or something? It seems odd to have kompose generate invalid manifests, particularly when you can just use jq to filter the output already.

**Comment by sstarcher** [comment]
Invalid manifests? A pod is a valid manifest.

**Comment by ericchiang** [comment]
Ah, right. Sorry, brain fart.

**Comment by surajssd** [comment]
@sstarcher this is not what kompose would do, but if you want pod per docker-compose service and not have a controller, you can use docker-compose's `restart` construct, read about it here https://github.com/kubernetes-incubator/kompose/blob/master/docs/user-guide.md#restart

**Comment by sstarcher** [comment]
@surajssd sounds fine I'll just manipulate the output

**Comment by sstarcher** [comment]
@surajssd that's exactly what I wanted.  #334

**Comment by surajssd** [comment]
@sstarcher that solves it then :+1:
