### ISSUE TITLE
Why do tests take so long to run?

### ISSUE THREAD

**Issue by cdrage** [kubernetes-incubator/kompose#247]
I'm trying to figure out why the tests take so long to run, even though we only have one test file: `kubernetes_test.go`.

When I run `htop` during the test build, it's showing a lot of vendor tests being ran, is this normal?

**Comment by sebgoa** [comment]
yes that is a big one. I noticed the same thing.

We need to fix this asap.

**Comment by ericchiang** [comment]
> When I run htop during the test build, it's showing a lot of vendor tests being ran, is this normal?

`go test ./...` will run test files in the `vendor` directory. Are you not filtering those packages out properly?

**Comment by kadel** [comment]
Times on my laptop:

go test arguments     |  duration
---------------------------|-------------
`-cover -race `|   208.25s 
` -cover `         |    14.48s  
no args                     | 14.35s

I've run it like this
`time go test  -v $( go list github.com/kubernetes-incubator/kompose/... | grep -v '/vendor/' )`


So it looks like race condition detector is to blame. 
I don't think that we need it in automated tests.

**Comment by cdrage** [comment]
@kadel 

Create a PR for this :) #263

**Comment by ericchiang** [comment]
@kadel that's because you're not caching the build assets and need to rebuild every time.

```
$ pkgs=$( go list github.com/kubernetes-incubator/kompose/... | grep -v '/vendor/' )
$ # install test dependencies
$ go test -v -i -race $pkgs
$ time go test -race $pkgs
?   	github.com/kubernetes-incubator/kompose	[no test files]
ok  	github.com/kubernetes-incubator/kompose/cli/app	1.062s
?   	github.com/kubernetes-incubator/kompose/cli/command	[no test files]
?   	github.com/kubernetes-incubator/kompose/pkg/kobject	[no test files]
?   	github.com/kubernetes-incubator/kompose/pkg/loader	[no test files]
?   	github.com/kubernetes-incubator/kompose/pkg/loader/bundle	[no test files]
?   	github.com/kubernetes-incubator/kompose/pkg/loader/compose	[no test files]
?   	github.com/kubernetes-incubator/kompose/pkg/transformer	[no test files]
ok  	github.com/kubernetes-incubator/kompose/pkg/transformer/kubernetes	1.070s
?   	github.com/kubernetes-incubator/kompose/pkg/transformer/openshift	[no test files]
?   	github.com/kubernetes-incubator/kompose/version	[no test files]

real	0m6.592s
user	0m15.668s
sys	0m2.012s
```

Please please please keep the race detector enabled. It's a critical tool for finding race bugs.

**Comment by kadel** [comment]
OK lets keep `-race`.

I don't know that much about Go testing, I'll have to do more reading.

What is `-i` doing?

**Comment by ericchiang** [comment]
> What is -i doing?

Installing test dependencies. Similar to `go build` vs `go install`: http://dave.cheney.net/2014/06/04/what-does-go-build-build

Since the race detector requires recompiling dependencies, you're noticing the lack of this flag more.

**Comment by cdrage** [comment]
I'm going to close this for now. The length of the tests is negligible since the main blocker of this is the time it takes to initially compile.

While watching `htop` I see that it's compiling files from the `vendor` directory. Specifically Kubernetes.

Once Kompose has compiled, tests are ran in less than 5 seconds.
