### ISSUE TITLE
Track release goals with GitHub milestones

### ISSUE THREAD

**Issue by ericchiang** [kubernetes-incubator/kompose#250]
Part of being in the kubernetes-incubator is regular releases and conveying the development roadmap. While the README has a section about this, it's pretty out of date, and only addresses extremely high level goals.

As discussed on the #kompose slack channel, consider using GitHub milestones to address this.

cc @dustymabe @sebgoa

**Comment by dustymabe** [comment]
great idea Eric, @sebgoa can we come up with a list of things that can be achieved via a F2F meeting at kubecon? coming up with a list of milestones would be a good thing to do there when a part of the team is meeting face to face.

**Comment by sebgoa** [comment]
yes, I will remove the roadmap in the README in a small PR.

I created 2 milestones and labels....now we need to tag the issues properly to fill up the milestone.

Still need criteria that trigger the actual release...

**Comment by ericchiang** [comment]
@sebgoa thanks! Couple of follow up todo's before I close this issue.

* Someone should update the README to refer to the milestones.
* It seems odd to have a point release milestone since kompose only has one branch. How would you release 0.2.1 features without 0.3.0 features commit to master getting in.
* There need to be more high level feature issues. As @dustymabe pointed out kubecon might be a good place to spec some of these out.

**Comment by sebgoa** [comment]
no need to close. This was just a five minute thing.

We need a release process and and write up about how to tag issues and create milestone.

**Comment by sebgoa** [comment]
cc #315
