### ISSUE TITLE
Issues regarding CLI. Perhaps switching to Cobra?

### ISSUE THREAD

**Issue by cdrage** [kubernetes-incubator/kompose#253]
Recently I've been digging through urfave trying to find a solution for  #239 (https://github.com/urfave/cli/pull/399 was the fix).

Most of these edge-cases have already been proven and used in another CLI library called Cobra. I recently found it _very_ useful and much cleaner than urfave when adding new commands and improving the UX. 

Lot's of major projects using it as well as the lead developer recently joining the Golang team :) 

Given a PR, would people be willing to switch? 

https://github.com/spf13/cobra

**Comment by surajssd** [comment]
+1 for cobra, but we need to make sure we don't introduce new bugs.

**Comment by kadel** [comment]
+1 for cobra also. It looks like it is more powerful. Plus we already have it in Kompose codebase as Kubernetes dependency.

**Comment by ngtuna** [comment]
+1 Cobra is great. The original kompose was a fork of libcompose that's why it's using urfave/cli.

**Comment by sebgoa** [comment]
#304

**Comment by kadel** [comment]
closing as #304 was merged
