### ISSUE TITLE
Change strategy for Deployments/DeployementConfigs

### ISSUE THREAD

**Issue by kadel** [kubernetes-incubator/kompose#264]
When Kompose creates Deployments there is no strategy specified -  RollingUpdate is default.

This might cause problems with some applications using volumes, like databases.

We should consider changing strategy to Recreate, this should be safer option.

**Comment by ngtuna** [comment]
Yes agree @kadel. That's something we thought about. Ref #17

**Comment by ngtuna** [comment]
I'm seeing there are more and more specific options coming like deployment strategy, volume size, and so on. And we are fixing these options in code. Should we make a flexible configuration strategy like putting them into profile in the preference file, or adding kompose-specific labels. They should not be declared in flags as user doesn't want to remember all of these details in a single command.

**Comment by surajssd** [comment]
Also consider some applications take time to start, so having Recreate by default might cause problems there. I think the default of RollingUpdate is there for a reason.

**Comment by kadel** [comment]
@ngtuna 
> Should we make a flexible configuration strategy like putting them into profile in the preference file, or adding kompose-specific labels. They should not be declared in flags as user doesn't want to remember all of these details in a single command

Agreed, I think that we already started with labels, so those thinks should be configurable via labels.

@surajssd 
> Also consider some applications take time to start, so having Recreate by default might cause problems there. I think the default of RollingUpdate is there for a reason.

I don't know. I would rather have small interruption then corrupting my database, and potentially loosing all my data :wink:  
If we do it configurable via labels, RollingUpdate should be default (that i agree), but if we have to choose one without allowing user to change it , than it should be Recreate.

**Comment by kadel** [comment]
I just thought how we can do it "in between" ;-) If docker-compose service doesn't have volumes we can safely use RollingUpdate and only if service has volume we will default to Recreate. 

Thoughts? :-)

**Comment by containscafeine** [comment]
@kadel taking this up!
