### ISSUE TITLE
Make kompose keep trying its job

### ISSUE THREAD

**Issue by ngtuna** [kubernetes-incubator/kompose#270]
I would suggest to make kompose keep trying its job when an error occurs. Currently we throw the error and stop doing convert/up/down immediately. I would prefer a better behavior like this:

```console
$ kompose --file kadel.yml up 
We are going to create Kubernetes Deployments, Services and PersistentVolumeClaims for your Dockerized application. 
If you need different kind of resources, use the 'kompose convert' and 'kubectl create -f' commands instead.

INFO[0001] Successfully created Service: frontend       
INFO[0002] Successfully created Service: mongodb        
INFO[0002] Successfully created Service: backend        
INFO[0002] Successfully created Deployment: frontend    
INFO[0003] Successfully created Deployment: mongodb     
FATA[0003] Error while deploying application: persistentvolumeclaims "mongodb-claim0" already exists . We will keep deploying application.
INFO[0003] Successfully created Deployment: backend

$ kompose --file kadel.yml down
INFO[0002] Successfully deleted Service: backend        
INFO[0002] Successfully deleted Service: frontend       
INFO[0003] Successfully deleted Service: mongodb        
FATA[0003] Error while deleting application: deployments.extensions "backend" not found. We will keep deleting resources.
INFO[0002] Successfully deleted Service: frontend       
INFO[0003] Successfully deleted Service: mongodb
```

Probably it's okay to stop the `kompose up` immediately at the time of error happening, but keep the `kompose down` working will help to clean the resources better.

**Comment by ngtuna** [comment]
Probably add `--force` flag

**Comment by kadel** [comment]
> Probably it's okay to stop the kompose up immediately at the time of error happening, but keep the kompose down working will help to clean the resources better.

+1

I agreed for `down` it should continue cleaning even after unsuccessful deletion of one object.

For `up` it doesn't make sense  to continue because you will end up with application that is not completely deployed. But instead  if there is and error during `up` we should clean up objects that were already created.

**Comment by ngtuna** [comment]
@kadel Totally agree.

**Comment by containscafeine** [comment]
Hey @ngtuna, are you working on this?
