### ISSUE TITLE
CPUSet is read and but do not map to k8s

### ISSUE THREAD

**Issue by surajssd** [kubernetes-incubator/kompose#272]
We do read the `CPUSet` from docker-compose file and do not map it to any kubernetes constructs. So either add support for it or add it to unsupported keys.

**Comment by cdrage** [comment]
Hmm. Seems that a limit range must be added in order to add this to Kubernetes! 

http://kubernetes.io/docs/admin/limitrange/

I'm assuming we should warn the user if CPUSet is set?

**Comment by surajnarwade** [comment]
@surajssd @cdrage as CPUset is mapped to any k8s key, shall we add it to unsupported keys.

**Comment by surajssd** [comment]
@surajnarwade yes SGTM, go ahead with it!
