### ISSUE TITLE
Support multiple compose files

### ISSUE THREAD

**Issue by ankon** [kubernetes-incubator/kompose#275]
In my environment I have multiple docker-compose files: one "base", and then some more to enable additional services/options. These additional docker-compose files override/modify the base image settings.

It would be nice if kompose supported this natively: `kompose -f base.yml -f mod.yml -f other-mod.yml convert`.

Currently it simply ignores all but the last-mentioned file.

**Comment by ankon** [comment]
> Currently it simply ignores all but the last-mentioned file.

This probably counts as "input argument validation", i.e. https://github.com/kubernetes-incubator/kompose/issues/87 is related.

**Comment by surajssd** [comment]
@ankon or this could also look like 

```
kompose -f base.yml,mod.yml,other-mod.yml convert
```

**Comment by ankon** [comment]
In principle, yes. But I think it would be good to stay consistent with docker-compose's behavior here.

**Comment by cdrage** [comment]
I can work on this once #304 is merged :) Add supported for multiple file import.
