### ISSUE TITLE
Add coveralls

### ISSUE THREAD

**Issue by sebgoa** [kubernetes-incubator/kompose#281]
to track our unit test coverage, we should setup coveralls.io, it is used in the main repo.

then we need to work on the unit-tests

**Comment by cdrage** [comment]
@sebgoa someone will have to login to coveralls.io to enable it, but I've created #287

**Comment by sebgoa** [comment]
@sarahnovotny sorry to ping you directly, but do you know how we can enable `coveralls` for kompose. I am assuming there is a kubernetes project account.

**Comment by sebgoa** [comment]
In the meantime, I logged into coveralls and requested access for kubernetes-incubator, no clue to whom the request went. Will see.

**Comment by cdrage** [comment]
@sebgoa @sarahnovotny thank you both. Yeah, the PR (https://github.com/kubernetes-incubator/kompose/pull/287) failed due to no access (timeout to coveralls)
