### ISSUE TITLE
A better missing port warning message

### ISSUE THREAD

**Issue by cdrage** [kubernetes-incubator/kompose#291]
When encountering the warning from: https://github.com/kubernetes-incubator/kompose/blob/master/pkg/transformer/kubernetes/k8sutils.go#L232 I don't know what it specifically means when it says that "port" is missing.

What am I missing here? I don't believe I need to explicitly supply the port, correct?

**Comment by surajssd** [comment]
Discussion on similar lines happened about detecting ports exposed from image itself at https://github.com/kubernetes-incubator/kompose/issues/146

I am +1 for better warning message or something like that.

**Comment by kadel** [comment]
https://github.com/kubernetes-incubator/kompose/pull/157 should solve this.

**Comment by sebgoa** [comment]
Yes, I am closing. I will get back to #157
