### ISSUE TITLE
Interactive / work-through-each-step mode.

### ISSUE THREAD

**Issue by cdrage** [kubernetes-incubator/kompose#292]
So at the moment you simply run `kompose convert` and that's it. Sometimes you can pass in:
```
   --chart, -c                          Create a Helm chart for converted objects
   --deployment, -d                     Generate a Kubernetes deployment object (default on)
   --daemonset, --ds                    Generate a Kubernetes daemonset object
   --replicationcontroller, --rc        Generate a Kubernetes replication controller object
```

However, I'd be **awesome** to add an interactive mode where it will walk you through each step.

For example, when encountering a service *without* a port within `docker-compose.yml`, `kompose` should output the implicit section and ask the user what port that service is using. This is required for Kubernetes conversion.

The same goes for volumes which are binded to the host within `docker-compose.yml` but cannot be converted to an equivalent Kubernetes artifact.

**Comment by ngtuna** [comment]
Yeah this used to be discussed during summer. We should keep it in mind and for some special cases need interactive mode we will discuss (probably on kompose call). Also, in those special cases, I would suggest we should provide both (for example, adding `--silent` flag for non-interactive mode)

**Comment by containscafeine** [comment]
@cdrage @ngtuna how do we proceed with this?

Instead of a `--silent` flag, should be instead have `-i, --interactive` flag?

Also, the possibilities of going interactive for a particular option/behavior are quite a few, so should we do this iteratively instead? e.g., let's start with adding one for when the ports are not found, and keep on sending PRs as and when we go?

Thoughts?
CC: @kadel @surajssd

**Comment by kadel** [comment]
What would be use cases for interactive mode? What question would like to ask?

Ports are solved and we don't need interactive mode for that.

**Comment by containscafeine** [comment]
@kadel - umm..., something like - 

- no value set for environment variable $image, enter now :
- build specified, but no git repo initialized, enter now:

There can be more cases as and when we go, WDYT?

**Comment by surajssd** [comment]
We first need to create a layer around the way data comes in. With this addition data will be coming in from cmd line flags, defaults and interactive mode.

this will help us do validation from one place only.

**Comment by cdrage** [comment]
I'm going to close this for now.
