### ISSUE TITLE
kompose 0.1.2 fails to parse key-only variables in environment section, does work with lists but generates invalid k8s resources

### ISSUE THREAD

**Issue by whereisaaron** [kubernetes-incubator/kompose#303]
`kompose version 0.1.2 (92ea047)`

I was exciting to try out kompose to help my colleague migrate to k8s, but I could not find any of our dock-compose files that kompose could parse. They all reported errors for the 'environment' section, such as:

```
ERRO[0000] Could not parse config for project project : yaml: line 88: could not find expected ':'
```
or
```
FATA[0000] Failed to load compose file: Service 'mysql' configuration key 'environment' contains an invalid type, it should be an array or object
Service 'phpmyadmin' configuration key 'environment' contains an invalid type, it should be an array or object
Unsupported config option for phpmyadmin service: 'PMA_HOST'
```

It looks like the kompose parser doesn't support the full docker-compose spec for environment variables. If you want to pass your build environment value into the same-named environment variable in your container, you just need to name the variable in the environment section of the docker-compose file, e.g.

```
    environment:
      MYSQL_HOST
      MYSQL_DATABASE
      MYSQL_USER
      MYSQL_PASSWORD
```

This is documented in the docker-compose spec page for environment variables here:

https://docs.docker.com/compose/compose-file/#/environment
**"Environment variables with only a key are resolved to their values on the machine Compose is running on, which can be helpful for secret or host-specific values."**

I was able to work around this for the kompose parser by adding colons to each item, but I think that might break docker-compose as all the variables will get blank/empty values.
```
    environment:
      MYSQL_HOST:
      MYSQL_DATABASE:
      MYSQL_USER:
      MYSQL_PASSWORD:
```

Converting the environment section to a sequence also helped kompose parse it, though again not sure if docker-compose will support this form?
```
    environment:
      - MYSQL_HOST
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
```

But even with both those work-arounds kompose generated only name fields for kubernetes, with no value, which isn't going to work when sent to a cluster. 

```
                "env": [
                  {
                    "name": "MYSQL_DATABASE"
                  },
                  {
                    "name": "MYSQL_USER"
                  },
                  {
                    "name": "MYSQL_PASSWORD"
                  },
                  {
                    "name": "MYSQL_ROOT_PASSWORD"
                  }
                ],
```

I think kompose should generate value properties with the actual value of the environment variables (from the kompose environment).

When we manually convert docker-compose file some of those environment fields become Secret or ConfigMap entries, but probably injecting the value is best default behavior for kompose is order to allow `kompose up` to work?

**Comment by sebgoa** [comment]
Hi, thanks for reporting this.
Docker compose reads the environment variable and uses the same as key. which we don't do (checking on it now)

For kompose, this should work:

```
environment:
  - MYSQL_HOST: $MYSQL_HOST
  - MYSQL_DATABASE: $MYSQL_DATABASE
  - MYSQL_USER: $MYSQL_USER
```

We will check it carefully and patch kompose to support the case you mentioned.

**Comment by ngtuna** [comment]
Thanks @whereisaaron I submitted a patch above for your case.

**Comment by kadel** [comment]
Hi, @whereisaaron 

Does this work for you with docker-compose?
```
    environment:
      MYSQL_HOST
      MYSQL_DATABASE
      MYSQL_USER
      MYSQL_PASSWORD
```

I've tried that and I got
```
ERROR: The Compose file './docker-compose.yml' is invalid because:
services.foo.environment contains an invalid type, it should be an object, or an array
```

I think that  that only possible options for this even with docker-compose are
```
    environment:
      MYSQL_HOST:
```
or
```
    environment:
      - MYSQL_HOST
```

**Comment by ngtuna** [comment]
@kadel Yes you're correct. it doesn't work on docker-compose. Tested with latest docker-compose 1.9.0

**Comment by singhvirendra18gmailcom** [comment]
Hi I am getting following issue on "Kompose convert -c" 

Service 'tomcat' configuration key '0' contains an invalid type, it should be a string.

Thanks in advance.

**Comment by cdrage** [comment]
> Hi I am getting following issue on "Kompose convert -c"
> 
> **Service 'tomcat' configuration key '0' contains an invalid type, it should be a string.**
> 
> Thanks in advance.

This is an issue from 2016, can you open a separate issue detailing your docker compose file + full output?

Thanks!
