### ISSUE TITLE
Default to YAML output

### ISSUE THREAD

**Issue by ankon** [kubernetes-incubator/kompose#306]
As per the "[best practices](http://kubernetes.io/docs/user-guide/config-best-practices/)":
> Write your configuration files using YAML rather than JSON. They can be used interchangeably in almost all scenarios, but YAML tends to be more user-friendly for config.

I've not followed that advice when I used kompose to convert my docker-compose files, and now need to reconvert+reapply adjustments (or convert via JSON->YAML converter).

Arguments for YAML:
* YAML allows comments
* All examples in kubernetes documentation are YAML

**Comment by surajssd** [comment]
+1

**Comment by cdrage** [comment]
Totally agree on my part.

**Comment by cdrage** [comment]
I can implement this after #304 is added since this involves changing a few of the CLI parameters.

**Comment by cdrage** [comment]
@ngtuna @sebgoa Can I be added to the repo so I can self-assign / labels?

**Comment by kadel** [comment]
I don't think that we should block this on #304 
This will be easy fix and it would be great to get it finally in.

My proposal for this is:
 - add new `--json -j` option to `convert` command, that will export to JSON only if set.
 - change  default  format to yaml if no option is specified
 - when user sets `--yaml` show warning that this option is deprecated and that yaml format is default.

I would even consider dropping JSON support all together. I don't know if it is something that anyone will use.
