### ISSUE TITLE
Update roadmap / split into ROADMAP.md with relevant information

### ISSUE THREAD

**Issue by cdrage** [kubernetes-incubator/kompose#315]
So a few things look out of date / completed in the road map within README.md.

I say we split this into ROADMAP.md and have a more up-to-date / future plan. Including listing all past "accomplishments".

**Comment by kadel** [comment]
Can we use just Issues and Milestones for roadmap and planing?

**Comment by cdrage** [comment]
@kadel One of my reasonings is in regards to being accepted into the Kubernetes repo. It was noted to have a clear roadmap for the future in regards to release / features / implementations.

So having a ROADMAP.md in the readme similar to: https://github.com/coreos/rkt/blob/master/ROADMAP.md

**Comment by sebgoa** [comment]
I am going to close this in favor of #250 which talks about removing the roadmap items in the README.

So feel free to send a PR for this, I had said I would do it...

For the record, the simple bullet list roadmap was just to get a few ideas for the incubator proposal.
