### ISSUE TITLE
restart: Unsupported value: "OnFailure": supported values: Always 

### ISSUE THREAD

**Issue by surajssd** [kubernetes-incubator/kompose#318]
Using this docker-compose file

```yaml
$ cat docker-compose.yml 
version: "2"
services:
  mariadb:
    image: centos/mariadb
    restart: on-failure
```

which fails as
```bash
$ kompose up
WARN[0000] [mariadb] Service cannot be created because of missing port. 
We are going to create Kubernetes Deployments, Services and PersistentVolumeClaims for your Dockerized application. 
If you need different kind of resources, use the 'kompose convert' and 'kubectl create -f' commands instead. 

FATA[0000] Error while deploying application: Deployment.extensions "mariadb" is invalid: spec.template.spec.restartPolicy: Unsupported value: "OnFailure": supported values: Always 
```

when converted it looks like this:

```yaml
$ cat mariadb.yml 
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: mariadb
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: mariadb
    spec:
      containers:
      - image: centos/mariadb
        name: mariadb
        resources: {}
      restartPolicy: OnFailure
status: {}
```

so this cannot be `OnFailure` it always has to be `Always` which stops us from using `docker-compose`'s `restart: on-failure` to simulate kubernetes jobs.

**Comment by surajssd** [comment]
So I tried this in continuation with discussion at https://github.com/kubernetes-incubator/kompose/issues/236#issuecomment-262592263

**Comment by surajssd** [comment]
But this is perfectly valid thing 
```yaml
$ cat pod-maria.yml 
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  name: mariadb
spec:
  containers:
  - image: centos/mariadb
    name: mariadb
  restartPolicy: OnFailure
```

a pod without controller can have `restartPolicy` as `OnFailure`

**Comment by kadel** [comment]
I'm afraid that this doesn't have easy solution.
I don't think that we can create just pod if there is `restartPolicy: on-failure` in docker-file.

But we could get away with just ignoring it, and showing warning explaining that this is ignored and `Always` will be used instead)

**Comment by surajssd** [comment]
>But we could get away with just ignoring it, and showing warning explaining that this is ignored and Always will be used instead)

@kadel but then this is not solving our original problem of how do we simulate k8s-job like workflow with kompose and docker-compose?

**Comment by kadel** [comment]
I'm not even sure if we should simulate Kubernetes job.

You propose creating Job if there is `restart: on-failure`?

**Comment by ngtuna** [comment]
so with #334 pod will be created instead of Job if there is `restart: on-failure`.

**Comment by surajssd** [comment]
@ngtuna yes you are right!

**Comment by surajssd** [comment]
With https://github.com/kubernetes-incubator/kompose/pull/334 merged this issue is solved.

**Comment by mhyousefi** [comment]
So, what is the point of having `deployment.spec.template.spec.restartPolicy` if `Always` is only  allowed option?????

Also, I suppose one could use `backoffLimit: 0`, though it doesn't seem like a robust solution as the reason why the pod terminated could very well be an actual failure!
