### ISSUE TITLE
kompose errors identifying string in docker-compose

### ISSUE THREAD

**Issue by surajssd** [kubernetes-incubator/kompose#320]
when using docker-compose file 
```yaml
version: "2" 
services:
  mariadb:
    image: centos/mariadb
    restart: no
```

failed saying val should be string
```bash
$ kompose convert --stdout > /dev/null 
ERRO[0000] Could not parse config for project onfailure : Service 'mariadb' configuration key 'restart' contains an invalid type, it should be a string. 
FATA[0000] Failed to load compose file: Service 'mariadb' configuration key 'restart' contains an invalid type, it should be a string. 
$ echo $?
1
```

but this works fine

```yaml
version: "2" 
services:
  mariadb:
    image: centos/mariadb
    restart: on-failure
```

```bash
$ kompose convert --stdout > /dev/null 
WARN[0000] [mariadb] Service cannot be created because of missing port.
$ echo $?
0
```

also this works fine

```yaml
version: "2" 
services:
  mariadb:
    image: centos/mariadb
    restart: "no"
```

**Comment by kadel** [comment]
I think that this might be an issue with libcompose.  
Does `restart: no` works with `docker-compose`?

**Comment by surajssd** [comment]
@kadel found the issue, it reads `no` as boolean this is inherent to `yaml`

>A Boolean represents a true/false value. Booleans are formatted as English words (“true”/“false”, “yes”/“no” or “on”/“off”) for readability and may be abbreviated as a single character “y”/“n” or “Y”/“N”.

Source: http://yaml.org/type/bool.html

**Comment by surajssd** [comment]
Closing since we cannot do anything with the yaml spec.
