### ISSUE TITLE
Functional tests for OpenShift down

### ISSUE THREAD

**Issue by procrypt** [kubernetes-incubator/kompose#323]
Need functional tests for #280

**Comment by ericchiang** [comment]
Shouldn't this be addressed in the PR? Why the extra issue?

**Comment by kadel** [comment]
Almost all code in this touches OpenShift cluster.
To test this, it will require setting up OpenShift cluster or mocking its api.

Same situation is with up/down for k8s. We will have to figure out how we will test all this.

We don't want to block PR on that. So we created this separate issue.

**Comment by surajnarwade** [comment]
@cdrage @kadel, we can close this issue as functional tests are being added for `kompose down` by @ashetty1
