### ISSUE TITLE
Determine group membership

### ISSUE THREAD

**Issue by sebgoa** [kubernetes-incubator/kompose#327]
Currently it seems that I cannot add folks to the contributor group.

We need a group that can attache labels, and assign tickets to themselves.

+ determine who gets write access to the repo.

There is no incubator wide rules on this afaik.

**Comment by bgrant0607** [comment]
@sebgoa As team maintainer, you can add team members, you just can't add org members -- only org owners can do that.

Related:
https://github.com/kubernetes/community/issues/142

Any ideas, @philips?

**Comment by bgrant0607** [comment]
https://help.github.com/articles/adding-organization-members-to-a-team/

**Comment by sebgoa** [comment]
I always feel stupid with these...but, since I am not an org owner I cannot send an invite to a non-org member. Even if I am the team maintainer, I can only invite org members.

we are trying to add @cdrage , ideally to just give permissions to add labels and assign issues to himself. But I don't think there is that granularity in teams.

**Comment by bgrant0607** [comment]
cc @grodrigues3 @fejta

**Comment by surajssd** [comment]
Sorry about that missed clicking

**Comment by bgrant0607** [comment]
Invited @cdrage to org.
