### ISSUE TITLE
yml support

### ISSUE THREAD

**Issue by vasil-moneybird** [kubernetes-incubator/kompose#336]
Do you guys plan to bring support for yaml files. Currently `kompose` generates JSON files only.

**Comment by pradeepto** [comment]
Hi @vasil-moneybird 

Kompose already supports conversion to YAML format. Use the `-y` switch to the commandline and  read more about it in the user [guide](https://github.com/kubernetes-incubator/kompose/blob/master/docs/user-guide.md). 

And here's the [issue]( https://github.com/kubernetes-incubator/kompose/issues/306) for converting to YAML as default.

**Comment by vasil-moneybird** [comment]
Cool thanks, I guess I didn't search enough :)
