### ISSUE TITLE
Tests before merge

### ISSUE THREAD

**Issue by surajssd** [kubernetes-incubator/kompose#349]
After a maintainer does merge, tests should run with PR rebased with master, and if all tests pass then only merge should happen. I think this can be implemented with travis.

**Comment by cdrage** [comment]
@surajssd I've gone ahead and enabled this within GitHub. Tests are now required to pass before merging in (can't merge in without travis being :green_heart: )

**Comment by surajssd** [comment]
@cdrage awesome thing!
