### ISSUE TITLE
add support for docker-compose.yaml besides docker-compose.yml

### ISSUE THREAD

**Issue by containscafeine** [kubernetes-incubator/kompose#352]
It would be great if kompose would also look for `docker-compose.yaml` besides `docker-compose.yml` in the current directory.

**Comment by surajssd** [comment]
I guess default should always be one value.

**Comment by containscafeine** [comment]
@surajssd IIRC, docker-compose supports both, should we or not?

**Comment by surajssd** [comment]
i guess we should!

**Comment by procrypt** [comment]
@containscafeine @surajssd can any one of you assign it to me.
