### ISSUE TITLE
"Failed to unmarshal MaporSlice" attempt to convert Sentry quick start

### ISSUE THREAD

**Issue by ncoghlan** [kubernetes-incubator/kompose#357]
I attempted to use the Fedora `kompose` package to convert https://github.com/getsentry/onpremise to Kubernetes/OpenShift and got the following error:

```
ERRO[0000] Could not parse config for project sentryonopenshift : Failed to unmarshal MaporSlice 
FATA[0000] Failed to load compose file: Failed to unmarshal MaporSlice 
```

The Fedora package was last updated in October though, so I'm going to try building from source and see if that works:

```
$ rpm -qa kompose
kompose-0.1.2-0.1.git92ea047.fc25.x86_64
```

**Comment by ncoghlan** [comment]
Building from source gives exactly the same error.

**Comment by surajssd** [comment]
@ncoghlan tracked in library used by kompose called libcompose https://github.com/docker/libcompose/issues/428

**Comment by surajssd** [comment]
@ncoghlan I applied following diff and it worked for me:
Ideally this should be solved in kompose/libcompose, but this could be short term solution for you to move forward:

```diff
$ git diff
diff --git a/docker-compose.yml b/docker-compose.yml
index ba5d198..8c42f6c 100644
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -36,7 +36,8 @@ services:
       - ./data/postgres:/var/lib/postgresql/data
 
   web:
-    extends: base
+    extends:
+      service: base
     links:
       - redis
       - postgres
@@ -46,7 +47,8 @@ services:
       - '9000:9000'
 
   cron:
-    extends: base
+    extends:
+      service: base
     command: run cron
     links:
       - redis
@@ -55,7 +57,8 @@ services:
       - smtp
 
   worker:
-    extends: base
+    extends:
+      service: base
     command: run worker
     links:
       - redis

```

**Comment by surajnarwade** [comment]
@kadel @surajssd @ncoghlan  , I have raised PR for this issue in libcompose which can be tracked here https://github.com/docker/libcompose/pull/457

**Comment by surajnarwade** [comment]
@kadel @surajssd @ncoghlan , PR for issue https://github.com/docker/libcompose/pull/457 in libcompose is merged now, I updated vendoring in PR https://github.com/kubernetes-incubator/kompose/pull/562, once that gets merged, this issue will be resolved.

**Comment by surajnarwade** [comment]
we can close this now as https://github.com/kubernetes-incubator/kompose/pull/454 is merged now

**Comment by kadel** [comment]
original issue is fixed, but deploying Sentry from https://github.com/getsentry/onpremise/ without modification will be tricky, as it heavily depends on `build`
