### ISSUE TITLE
Should we not generate PVC's by default?

### ISSUE THREAD

**Issue by cdrage** [kubernetes-incubator/kompose#376]
The current default is to generate a PVC with *only* 100Mb of available memory.

Ex:
```
WARN[0000] Unsupported depends_on key - ignoring
WARN[0000] Unsupported network_mode key - ignoring
WARN[0000] Volume mount on the host "./media" isn't supported - ignoring path on the host
WARN[0000] Volume mount on the host "./media" isn't supported - ignoring path on the host
```

Yet it still build PVC's. 

Should we (by default) NOT generate volume mounts?

**Comment by kadel** [comment]
I'm not sure if I understand :-( 
What are you proposing to do with volumes instead? 

We already had this discussion in some other issue. I still think that PVC is right approach here. 
And if for some reason you want to avoid that you can use `--emptyvols` option.

But I agree that 100Mb default is bad. We need to make this configurable for user.

**Comment by cdrage** [comment]
@kadel I find it odd that we have a default to 100Mb and the volumes are inherently not working correctly since it's ignored on the host.

**Comment by kadel** [comment]
The host part will always be a problem as we don't have easy way how to copy data from the machine to the cluster :-(

**Comment by surajssd** [comment]
> @kadel I find it odd that we have a default to 100Mb and the volumes are inherently not working correctly since it's ignored on the host.

@cdrage can you elaborate what do you mean here?

**Comment by cdrage** [comment]
@surajssd We default to 100Mb in PVC's and if PV's aren't setup on the cluster Kompose won't warn the user / fail since PVC's will be stuck in a pending state the entire duration.

**Comment by surajssd** [comment]
@cdrage yes PVCs will fail when PV is not provisioned, but then kompose right now generates configs that are cluster agnostic with little extra setup needed.

We can expect PV to be setup already.

**Comment by surajnarwade** [comment]
@kadel , @surajssd , @cdrage , as of now, should we add warning in kompose such as, 

```
WARN[0000] volume "data-volume" of size "100 Mi" created
```

**Comment by cdrage** [comment]
@surajnarwade IMO, INFO instead of WARN may be better.

**Comment by kadel** [comment]
yeh, this shouldn't be WARN.
And message should probably mention something about PVC requiring PV. But I don't know how to explain it in one or two sentences :disappointed:

**Comment by surajnarwade** [comment]
okay @kadel @cdrage  I would like to work on it then

**Comment by surajssd** [comment]
@surajnarwade assigned!

**Comment by surajssd** [comment]
@surajnarwade https://github.com/kubernetes-incubator/kompose/pull/519#issue-217506525 says that the PR fixes this issue partially, what is the current state? Should we re-open this issue?

**Comment by surajnarwade** [comment]
@surajssd , no need to reopen the issue
