### ISSUE TITLE
kompose down with openshift doesn't delete  BuildConfig

### ISSUE THREAD

**Issue by ashetty1** [kubernetes-incubator/kompose#382]
I tried running `kompose down` with the buildconfig example here: https://github.com/kubernetes-incubator/kompose/tree/master/examples/buildconfig

It doesn't delete the buildconfig. 

```bash
$ kompose --provider=openshift -f docker-compose.yml down
WARN[0000] [foo] Service cannot be created because of missing port. 
INFO[0000] Buildconfig using https://github.com/skippbox/kompose2.git::master as source. 
INFO[0001] Successfully deleted DeploymentConfig: foo   
INFO[0001] Successfully deleted ImageStream: foo
```
```bash
$ oc get bc
NAME      TYPE      FROM         LATEST
foo       Docker    Git@master   1
```

**Comment by procrypt** [comment]
@ashetty1 `buildconfig` support was not present when `kompose down` for openshift got merged. Thanks for reporting the issue.
@kadel I'm working on it.

**Comment by ashetty1** [comment]
Correct me if I am wrong, but it appears in my testing that this issue hasn't been fixed yet:

Before running `kompose down`:

`NAME          READY     STATUS      RESTARTS   AGE`
`foo-1-build   0/1       Completed   0          1m`
`foo-1-lv0q5   1/1       Running     0          29s`

Running `kompose down`:
INFO Buildconfig using https://github.com/kubernetes-incubator/kompose.git::HEAD as source. 
INFO Successfully deleted Service: foo            
INFO Successfully deleted DeploymentConfig: foo   
INFO Successfully deleted ImageStream: foo        
INFO Successfully deleted BuildConfig: foo        


Looks like the build pod doesn't get deleted: Output of `oc get pods`:

`NAME          READY     STATUS      RESTARTS   AGE`
`foo-1-build   0/1       Completed   0          2m`

**Comment by surajssd** [comment]
@ashetty1 I think this https://github.com/kubernetes-incubator/kompose/pull/483 will solve the problem!

**Comment by surajssd** [comment]
meanwhile keeping this open since this problem is not completelt solved!
