### ISSUE TITLE
Docker DAB support does not currently work (still in experimental)

### ISSUE THREAD

**Issue by cdrage** [kubernetes-incubator/kompose#390]
Converting the current example we have produces this error:
```
▶ ./kompose convert -f examples/docker-compose-bundle.dab
ERRO Could not parse config for project examples : yaml: unmarshal errors:
  line 24: cannot unmarshal !!str `0.1` into config.RawService 
FATA Failed to load compose file: yaml: unmarshal errors:
  line 24: cannot unmarshal !!str `0.1` into config.RawService 
```

**Comment by cdrage** [comment]
@ngtuna Any idea why this may be happening? I'm assuming problems with floating values not being converted.

**Comment by sebgoa** [comment]
I am proposing a GSoC project to improve the dab support:
https://github.com/cncf/soc

**Comment by cdrage** [comment]
@sebgoa Should we deprecate this feature since it's still experimental within Docker and at the moment doesn't work with Kompose?

**Comment by sebgoa** [comment]
if it does not work, it is a regression that we should fix.

**Comment by kadel** [comment]
Is DAB actually used somewhere? Do we know if someone is using dab even with docker?

**Comment by sebgoa** [comment]
Honestly I have not kept up with the dab development. but I will check.

**Comment by djkonro** [comment]
Please, I am interested in working on this project for the Google Summer of Code. I am very comfortable working with programming languages like Java, C/C++, Python and Go. I am very passionate about cloud and container technologies, and I would like to get some help that would enable me better familiarizing myself with the project. I am already familiar with Docker and Docker compose and I am currently familiarizing myself with Kubernetes.

**Comment by cdrage** [comment]
I believe this link: https://github.com/docker/docker/issues/26876 would be the best in terms of keeping track *IF* DAB comes out of being experimental.

It *has* happened in the past that an experimental feature wasn't accepted into Docker. So it'd be best to keep track of this while we continue to support development / improvements.

**Comment by cdrage** [comment]
I'm closing this for now until Docker figures out DAB's role.
