### ISSUE TITLE
Container Port and Node Port mapping default to open

### ISSUE THREAD

**Issue by cdrage** [kubernetes-incubator/kompose#391]
When mapping a port, for example:
```
- "80:80"
```

in the Docker Compose file. It's the same as simply doing

```
- "80"
```

Is this normal? Exposing the ports by default when converting them to a service?

**Comment by surajssd** [comment]
I think so, because if you don't create a service name resolution wont happen from other pods. And it's safe because services are by default exposed as `clusterIP` which is not accessible from outside cluster.

**Comment by cdrage** [comment]
Yeah, kind of realized that this issue was me just being a Kubernetes noob :) Closing! Thanks @surajssd
