### ISSUE TITLE
new behavior of `kompose up`

### ISSUE THREAD

**Issue by ngtuna** [kubernetes-incubator/kompose#40]
Like `docker-compose up`, `kompose up` transparently generates default objects and deploy to kubernetes.

**Comment by ngtuna** [comment]
Also, print suggestion to use kubectl to deploy other controllers and include non-supported fields warning

**Comment by ngtuna** [comment]
As `kompose` supports more than one provider, we should have `--provider` flag like this:

```console
kompose up --provider openshift
```
Default: Kubernetes (without --provider).

**Comment by ngtuna** [comment]
Reopen it for further enhancement:

- add `--provider` flag
- handling invalid converted k8s object

**Comment by ngtuna** [comment]
@surajssd how can `kompose` read OpenShift endpoint config ?

**Comment by surajssd** [comment]
@ngtuna OpenShift endpoint config as in similar to `~/.kube/config` ?

**Comment by ngtuna** [comment]
Really? OK so I'm thinking how we can add `kompose up --provider openshift`. What is process ? We need to have a `~/.kube/config` pre-configured to openshift endpoint. Then let kompose does the same with kubernetes. It is not really convenience, isn't it ?

**Comment by kadel** [comment]
I even think  that we can use same deploy function (from kubernetes) for deploying  to OpenShift. 
We just need to make sure that proper api all installed such as (`	_ "github.com/openshift/origin/pkg/deploy/api/install"`)
We might change that to `_ "github.com/openshift/origin/pkg//api/install"` to make sure that all openshift objects are included in schema

**Comment by ngtuna** [comment]
Ah.... I remember we discussed about preference file at https://github.com/skippbox/kompose/issues/39. So, if the preference file is used, we don't need `--provider` anymore, right ?

**Comment by kadel** [comment]
I've started working on adding `kompose up` for openshift.
I will brake it to multiple PRs and in every PR I'm going to reference this issue.

**Comment by dustymabe** [comment]
I think this can be closed now?

**Comment by ngtuna** [comment]
Yes
