### ISSUE TITLE
Tagging for 0.2.1 release

### ISSUE THREAD

**Issue by cdrage** [kubernetes-incubator/kompose#400]
Hey all,

I've closed the milestones for the 0.2.1 and 0.3.0 release since both were completed to 100%. Makes sense to go straight to a 0.2.0 release rather than arbitrarily skipping a major release number.

Should we tag all new bugs as part of the 0.2.1 release and all major changes as part of the 0.3.0 release?

**Comment by cdrage** [comment]
ping @kubernetes-incubator/maintainers-kompose

**Comment by kadel** [comment]
I don't know if I understand :-(

Does is make sense to plan like this if we are doing time based releases?

**Comment by cdrage** [comment]
I'm not *too* sure. But yeah, you are correct though. Since we are doing time-based releases, tagging wouldn't be necessary / as well as milestones.

How should we keep our progress instead / future features?

**Comment by kadel** [comment]
I was thinking that maybe just priorities might be enough. But I'm not sure about that, just an idea.

**Comment by cdrage** [comment]
Closing this for now as we've just had a successful 0.3.0 release as well as we're going forward with time-based releases :)
