### ISSUE TITLE
Improve error handling

### ISSUE THREAD

**Issue by kadel** [kubernetes-incubator/kompose#416]
In some places like for example [here](https://github.com/kubernetes-incubator/kompose/blob/master/pkg/transformer/kubernetes/kubernetes.go#L491) we are printing errors using `logrus.Fatalf` deep inside code.  

It would be better if function returned error that can be processed outside of this function (higher in call stack). Code will be cleaner and it will be easier to write unit tests.

I think that we should invest some time in cleaning all error handling in Kompose codebase.

**Comment by procrypt** [comment]
Printing errors using `logrus.Fatalf`,  will need unit test to run a seperate `subprocess` to test the functionality of the code.

**Comment by surajssd** [comment]
@procrypt I think what @kadel is trying to say here is that instead of any function doing random `logrus.Fatalf` we just change that function to return errors and the function calling it should gracefully do `logrus.Fatalf` with all the resources giving back to the pool if there are any.

**Comment by procrypt** [comment]
@surajssd  Yeah I got the point, what trying to say is that otherwise we need to do it in [this](https://github.com/kubernetes-incubator/kompose/issues/416#issuecomment-278547474) way, which might be a bit convoluted.

**Comment by surajssd** [comment]
>@surajssd Yeah I got the point, what I am trying to say is that otherwise we need to do it in this way, which might be a bit convoluted.

`this` is self pointing here.

**Comment by containscafeine** [comment]
@kadel taking this up!

**Comment by containscafeine** [comment]
FYI: I have done some work [here](https://github.com/containscafeine/kompose/tree/improve_error_handling)

Also, I will be using the github.com/pkg/errors package to wrap and push the errors up the call stack.

Just keeping everyone in the loop.
