### ISSUE TITLE
Unable to build from source

### ISSUE THREAD

**Issue by sambostock** [kubernetes-incubator/kompose#421]
I'm trying to create a [Homebrew](http://brew.sh/) formula for Kompose.

```
$ brew install -i kompose
==> Using the sandbox
==> Downloading https://github.com/kubernetes-incubator/kompose/archive/v0.2.0.tar.gz
Already downloaded: /Users/sam/Library/Caches/Homebrew/kompose-0.2.0.tar.gz
==> Entering interactive mode
Type `exit' to return and finalize the installation
Install to this prefix: /usr/local/Cellar/kompose/0.2.0
bash-3.2$ export GOPATH=`pwd`
bash-3.2$ echo $GOPATH
/private/tmp/kompose-20170210-81761-1bzgwbv/kompose-0.2.0
```

However, **I can't get the build to succeed**. I've tried all the build methods listed in [`README.md`](https://github.com/kubernetes-incubator/kompose/blob/master/README.md).

#### `make bin`
```
bash-3.2$ make bin
fatal: Not a git repository (or any of the parent directories): .git
make: glide: Command not found
go build -ldflags="-w -X github.com/kubernetes-incubator/kompose/version.GITCOMMIT=" -o kompose main.go
main.go:19:8: cannot find package "github.com/kubernetes-incubator/kompose/cmd" in any of:
	/usr/local/Cellar/go/1.7.5/libexec/src/github.com/kubernetes-incubator/kompose/cmd (from $GOROOT)
	/private/tmp/kompose-20170210-81761-1bzgwbv/kompose-0.2.0/src/github.com/kubernetes-incubator/kompose/cmd (from $GOPATH)
make: *** [bin] Error 1
```

#### `go build -o kompose main.go`
```
bash-3.2$ go build -o kompose main.go
main.go:19:8: cannot find package "github.com/kubernetes-incubator/kompose/cmd" in any of:
	/usr/local/Cellar/go/1.7.5/libexec/src/github.com/kubernetes-incubator/kompose/cmd (from $GOROOT)
	/private/tmp/kompose-20170210-81761-1bzgwbv/kompose-0.2.0/src/github.com/kubernetes-incubator/kompose/cmd (from $GOPATH)
```

#### `CGO_ENABLED=0 GO15VENDOREXPERIMENT=1 go build -o kompose main.go`
```
bash-3.2$ CGO_ENABLED=0 GO15VENDOREXPERIMENT=1 go build -o kompose main.go
main.go:19:8: cannot find package "github.com/kubernetes-incubator/kompose/cmd" in any of:
	/usr/local/Cellar/go/1.7.5/libexec/src/github.com/kubernetes-incubator/kompose/cmd (from $GOROOT)
	/private/tmp/kompose-20170210-81761-1bzgwbv/kompose-0.2.0/src/github.com/kubernetes-incubator/kompose/cmd (from $GOPATH)
```

#### `make cross`
```
bash-3.2$ make cross
fatal: Not a git repository (or any of the parent directories): .git
make: glide: Command not found
gox -os="darwin linux windows" -arch="386 amd64" -output="bundles/kompose_{{.OS}}-{{.Arch}}/kompose" -ldflags="-w -X github.com/kubernetes-incubator/kompose/version.GITCOMMIT="
/bin/sh: gox: command not found
make: *** [cross] Error 127
```

Unfortunately, I am not familiar with Go. Can anyone point me in the right direction?

**Comment by sebgoa** [comment]
FWIW, we had a very early formulae before the move to the incubator, but it was not a source build:
https://github.com/skippbox/homebrew-tap

Why do you want to compile after doing a `brew install` ? 

`brew install` should get you the binary directly.

**Comment by kadel** [comment]
@sambostock: 
It looks like your GOPATH is not right. This is reason you are getting `main.go:19:8: cannot find package "github.com/kubernetes-incubator/kompose/cmd" in any of:....`

`make: glide: Command not found` error should be fixed in the next version (once #418 is merged)


I was trying to do same thing yesterday :-). 

And this is what I come up with:

```ruby
class Kompose < Formula
  desc "Tool to move from `docker-compose` to Kubernetes"
  homepage "http://kompose.io"
  head "https://github.com/kubernetes-incubator/kompose.git"
  url "https://github.com/kubernetes-incubator/kompose/archive/v0.2.0.tar.gz"
  # url "https://github.com/kubernetes-incubator/kompose.git",
  #     :tag => "v0.2.0",
  #     :revision => "bf8a03f1e9ed7206a712b99f82e26911d7243003"

  depends_on "go" => :build

  def install
    ENV["GOPATH"] = buildpath
    dir = buildpath/"src/github.com/kubernetes-incubator/kompose"
    dir.install buildpath.children

    cd dir do
      system "make"
      bin.install "kompose"
    end
  end

  test do
    # TODO
    system "false"  
  end
end
```


It works, but has one small flaw. Our build script detects git revision so it can be displayed in `kompose version` output. Problem is that there is no revision to detect when it is build from release archive, and even if it is build by brew from git, it picks up revision of  homebrew-core not kompose :-(

**Comment by kadel** [comment]
@sambostock how it is going?
Were you able to build it?

**Comment by sambostock** [comment]
@kadel Someone else submitted a [formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/kompose.rb), so I didn't do any other work on it.

This issue can probably be closed. Thanks for checking in!

**Comment by kadel** [comment]
OK.
Kompose is in brew now, that is great new. Didn't noticed that someone else got it merged
