### ISSUE TITLE
.env file is checked at current directory instead of target directory

### ISSUE THREAD

**Issue by containscafeine** [kubernetes-incubator/kompose#426]
examples/docker-compose file -
```yaml
$ cat examples/docker-compose.yml 
version: "2"
services:
  web:
    image: $imagename
```

examples/.env file -
```shell
$ cat examples/.env 
imagename=batman
```

When I run,
`kompose  convert -f examples/docker-compose.yml`, the environment variable does not get substituted and I get
```shell
WARN The imagename variable is not set. Substituting a blank string. 
```

However, when I do,
```shell
cd examples/
kompose convert -f docker-compose.yml
```
the value is substituted.

So, kompose is looking for the .env file in the current directory instead of the target directory where the docker-compose file is present.

**Comment by surajssd** [comment]
@containscafeine thanks for the issue, have you checked if this is coming from libcompose? If yes maybe needs to be filed in upstream.

**Comment by surajnarwade** [comment]
@surajssd @containscafeine , issue is coming from libcompose and I filed it in upstream, it can be tracked here https://github.com/docker/libcompose/issues/443

**Comment by surajnarwade** [comment]
we should reopen this issue @kadel as its not fixed yet

**Comment by kadel** [comment]
It is actually OK.
According docker-compose to documentation `.env` files should be placed in current directory.
"Compose supports declaring default environment variables in an environment file named .env placed in the folder where the docker-compose command is executed (current working directory)." - https://docs.docker.com/compose/env-file/

**Comment by containscafeine** [comment]
@kadel @surajnarwade ack, but does it make sense for this to be a feature in kompose? Or maybe add a command line flag to specify the .env file?

**Comment by kadel** [comment]
Its docker-compose feature, so it makes sense to have it in Kompose
