### ISSUE TITLE
`make test-unit` does not run on uncomitted changes

### ISSUE THREAD

**Issue by surajssd** [kubernetes-incubator/kompose#427]
```bash
$ make test-unit
go test -ldflags="-w -X github.com/kubernetes-incubator/kompose/version.GITCOMMIT=1712634" -race -cover -v ./pkg/... ./cmd/... .
```

How do I run tests of kompose like it was before? I never had need to commit changes to test them?

**Comment by kadel** [comment]
I don't have to commit anything. Nothing changed there. `make test-unit` runs test on current state of the directory, doesn't matter if changes are commit or not, it doesn't even have to be git repo.

**Comment by surajssd** [comment]
yeah seems like I mis-understood something, sorry for the spam, closing this duplicate.
