### ISSUE TITLE
[Discuss] Find a good way to vendoring dependencies

### ISSUE THREAD

**Issue by ngtuna** [kubernetes-incubator/kompose#43]
Guys,

The current issue I am facing in kompose is finding a good solution to vendoring dependencies. As you know, kompose refers to some structs of libcompose and kubernetes in order to do mapping fields between them. While kompose depends on libcompose and kubernetes, both of them are sharing lot of common dependencies but with different revisions. The current code base is quite stable, but let's say now I have to upgrade libcompose revision in order to solve #11 and #4 (which I also have to upgrade docker/docker revision in order to get bundlefile struct), also in future we have to support k8s 1.4, 1.5, etc. 

#vendoring seems to be a hot issue to be discussed at GopherCon afaik...
Someone introduces me https://github.com/sdboyer/gps. I will take a look on it tomorrow.

Any idea?

**Comment by kadel** [comment]
Right now I'm facing same problem with OpenShift.
It gets even worse because OpenShift has dependency on its own fork of Kubernetes, I only hope that parts that we need, are going to work with upstream Kubernetes.

But I don't have any good solution so far :-(

**Comment by ngtuna** [comment]
Yeah. Well, finding a solution to tackle the problem completely is impossible at this moment. It is known as the diamond problem for dependencies. Somehow `godep` can help to flatten the vendored code. It takes a bit more time to discover alternative choices.

https://github.com/golang/go/wiki/PackageManagementTools

**Comment by runseb** [comment]
this might help https://github.com/rancher/trash

**Comment by ngtuna** [comment]
@runseb That's interesting to take a look. Let me see.

**Comment by surajssd** [comment]
@ngtuna found one more golang vendor manager https://github.com/Masterminds/glide not sure how good or bad it is, but [Kubernetes Helm](https://github.com/kubernetes/helm) uses it.

**Comment by ngtuna** [comment]
Still haven't started looking into them. At least we are still good with `Godeps`. 

@surajssd Yeah I know there are lot of projects using `Glide` for vendoring.. It seems to be a powerful tool to do that..

**Comment by ngtuna** [comment]
I should close this. We have chosen an alternative sword - glide.
