### ISSUE TITLE
Normalizing service name might break application

### ISSUE THREAD

**Issue by surajnarwade** [kubernetes-incubator/kompose#433]
cc @surajssd @containscafeine

**Comment by kadel** [comment]
Good catch.

But I'm afraid that only thing that we can do here is show warning and make it clear what we are doing with service names in documentation

**Comment by surajssd** [comment]
oops saw this after commenting on https://github.com/kubernetes-incubator/kompose/issues/420#issuecomment-285030347

**Comment by surajnarwade** [comment]
we can close this issue now
