### ISSUE TITLE
Add documentation for mem_limit

### ISSUE THREAD

**Issue by kadel** [kubernetes-incubator/kompose#435]
Add documentation for https://github.com/kubernetes-incubator/kompose/pull/414

**Comment by pradeepto** [comment]
Bumped into this issue while I was discussing other issues, I think we can close this issue. What do you think @kadel ?

**Comment by cdrage** [comment]
@pradeepto Still pending for this being merged https://github.com/kubernetes-incubator/kompose/pull/448 as it's part of the documentation :)

**Comment by kadel** [comment]
#448 was merged. That should be enough to document it for now.
