### ISSUE TITLE
Support for: stop_grace_period

### ISSUE THREAD

**Issue by cdrage** [kubernetes-incubator/kompose#440]
No error / warning when using this key.

**Comment by procrypt** [comment]
@cdrage Opened up an issue on `libcompose`.
https://github.com/docker/libcompose/issues/447

**Comment by gitlawr** [comment]
upstream issue was fixed and we should be able to move on

**Comment by surajssd** [comment]
@cdrage @surajnarwade asking out of curiousity, where does this map to in k8s? And in code are we handing this info to something?

**Comment by gitlawr** [comment]
@surajssd I think stop_grace_period can be mapped to Pod.Spec.TerminationGracePeriodSeconds.
This issue hasn't been solved yet. Still no warning/error when using this key.

**Comment by surajnarwade** [comment]
@surajssd , can you please reopen the issue  ?

**Comment by surajssd** [comment]
closed by #608
