### ISSUE TITLE
Inconsistency in build context

### ISSUE THREAD

**Issue by kadel** [kubernetes-incubator/kompose#445]
I have two docker-compose files, that should do the same thing

build.yaml
```yaml
version: "2"
services:
    foo:
        build: "./build"
        command: "sleep 3600"
```

context.yaml
```yaml
version: "2"
services:
    foo:
        build:
            context: "./build"
        command: "sleep 3600"
```

I'm in the directory that is one level up from the directory where those docker-compose files are.

If run convert on first file like this:
```
kompose --provider openshift convert --stdout -f compose-build-test/build.yaml
```
I get BuildConfig that has `contextDir: build`. That is corrent.

But If I use second file that is using expanded way to define build
```
kompose --provider openshift convert --stdout -f compose-build-test/context.yaml
```
I get BuildConfig with `contextDir: compose-build-test/build`, which is wrong.

I also found out that if I'm in the same directory where those docker-compose files are, everything works as expected.
```
~/tmp/compose-build-test  master ✗ 
▶ kompose --provider openshift convert --stdout -f build.yaml | grep contextDir                   
INFO Buildconfig using https://github.com/kadel/compose-build-test.git::master as source. 
      contextDir: build

~/tmp/compose-build-test  master ✗ 
▶ kompose --provider openshift convert --stdout -f context.yaml | grep contextDir
INFO Buildconfig using https://github.com/kadel/compose-build-test.git::master as source. 
      contextDir: build
```

**Comment by surajnarwade** [comment]
contextDir should always be with respect to root directory of git repository, I have added fix in PR #424

**Comment by kadel** [comment]
> contextDir should always be with respect to root directory of git repository, I have added fix in PR #424

hi @surajnarwade, thank  you for fixing it,  but it would be better to have this as separate PR

**Comment by surajssd** [comment]
master works like this for me now:

dir structure
```
✔ ~/tmp/buildcontextimproper [master L|✔] 
12:18 $ tree
.
├── build
└── compose-build-test
    ├── build.yaml
    └── context.yaml

2 directories, 2 files
```


```bash
$ kompose --provider openshift convert --stdout -f compose-build-test/build.yaml | grep -i context
INFO Buildconfig using https://mycode.com.git::master as source. 
      contextDir: compose-build-test/build
```

and 

```bash
$ kompose --provider openshift convert --stdout -f compose-build-test/context.yaml | grep -i context
INFO Buildconfig using https://mycode.com.git::master as source. 
      contextDir: compose-build-test/compose-build-test/build
```

**Comment by surajnarwade** [comment]
I have raised PR in libcompose regarding this and can be tracked here https://github.com/docker/libcompose/pull/450

**Comment by cdrage** [comment]
https://github.com/docker/libcompose/pull/450 Has been merged. Update vendoring?

**Comment by pradeepto** [comment]
@cdrage https://github.com/kubernetes-incubator/kompose/pull/562 Not sure why he closed it. He mentioned somewhere that his updating vendoring along with some other issue https://github.com/kubernetes-incubator/kompose/pull/454 . Not sure if that is a good idea. IMO, updating vendoring could have been an independent PR but I will let you and others take the call on this.

**Comment by cdrage** [comment]
@pradeepto 
Opened up #566 to solve this and get us up-to-date with vendoring.

**Comment by cdrage** [comment]
Reopening this! :+1: needs https://github.com/kubernetes-incubator/kompose/pull/424 to close

**Comment by surajnarwade** [comment]
@cdrage @surajssd we can close this issue now
