### ISSUE TITLE
Wrong version, again

### ISSUE THREAD

**Issue by louisremi** [kubernetes-incubator/kompose#461]
I just downloaded linux-0.3.0 and installed it. When I run `kompose version` I get `0.2.0 (10cff91)`.
Also, I gave 0.3.0 a try because I had troubles with underscores in volume names, and after running `kompose convert`, the underscore were still present. I'll try compiling from source to confirm, but could it be possible that the published version does not include that patch?

**Comment by kadel** [comment]
Hi @lavalamp,
You are right, we uploaded binary that is showing wrong version number in `kompose version` :-(
Binary is correct it is compiled from latest source (in time of the release). 

Underscore problem got fixed in service names, but not in volume names :-(
We will fix that.

**Comment by kadel** [comment]
@cdrage we need to do something to make sure that we don't release binaries with wrong version again.

**Comment by cdrage** [comment]
Yeah, this is totally my fault, I had forgotten to add a function from a previous project to this release script in regards to syncing with the master repo before upload / making of the binaries. 

I've fixed this in #465

**Comment by kadel** [comment]
this has been fixed, shouldn't happen again :-)
