### ISSUE TITLE
stripping kompose binary?

### ISSUE THREAD

**Issue by containscafeine** [kubernetes-incubator/kompose#463]
When doing a `go install`, the resulting binary is 73M, and on doing a `go install -ldflags "-s"`, I am getting a 38M binary, which is essentially stripping the binary.

We can achieve the same by using the `strip` command on the binary.

Should we strip the kompose binary and release it? This gets the size down by about 50%, however there may be some tradeoffs like -
- https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=717172

More on stripping golang binaries here -
- https://blog.filippo.io/shrink-your-go-binaries-with-this-one-weird-trick/

**Comment by surajssd** [comment]
Lets test on all arch with stripped binaries if functional test pass that should be good, then add it to the build script in Makefile.

**Comment by kadel** [comment]
I wouldn't worry about that right now. It might bring more troubles than benefits.

**Comment by ericchiang** [comment]
FYI, please don't do this https://twitter.com/davecheney/status/846844080227213312

**Comment by cdrage** [comment]
I agree with @kadel and @ericchiang

Let's close this for now and focus rather on removing the big dependencies / reducing the binary the library-way.
