### ISSUE TITLE
RFE: kompose up support specified namespace to deploy

### ISSUE THREAD

**Issue by zanhsieh** [kubernetes-incubator/kompose#473]
I propose to have following syntax cli for kompose:

```bash
$ kompose up --namespace dev
```

Behaviour expected:

- Deploy all docker-compose container(s) specified in `docker-compose.yml` into given kubernetes namespace (e.g. `dev` for example above) 

Usage:

- Help developer easy to deploy into certain / isolate namespace in kubernetes, e.g. dev, staging, uat, and production.

This request relates to following issue, but I don't see anything could do / work around with my proposed feature:

https://github.com/kubernetes-incubator/kompose/issues/162

Thanks.

**Comment by kadel** [comment]
Hi @zanhsieh,
adding `--namespace` is good idea it will make switching namespace more user friendly, thank you for bringing this up.

Currently you can deploy to different namespace  using `kompose up` only if you switch default namespace for `kubectl` before.

`~/.kube/config`.
```sh
# get current context
$ kubectl config get-contexts
CURRENT   NAME                                        CLUSTER                         AUTHINFO                              NAMESPACE
*         minikube                                    minikube                        minikube                              asdf
          myproject/10-34-129-45:8443/developer       10-34-129-45:8443               developer/10-34-129-45:8443           myproject


# set namespace for current context
$ kubectl config set-context minikube --namespace asdf
Context "minikube" set.

$ kompose up
```

**Comment by cdrage** [comment]
I agree that adding `--namespace` would be a good idea for Kompose up / down, especially since (ideally) we would want to test this against a test environment.

Having a INFO display what namespace is being deployed too at the time of `kompose up` and `kompose down` would also be beneficial.

**Comment by zanhsieh** [comment]
Another thing stuck in my mind was, should we also include `--force` switch? Ideas were:

1. If no given namespace existed, create one.
2a. [Ambiguous] if namespace given existed, wipe it out and create.
2b. [Ambiguous] if namespace given existed, merge and update whatever.
3. `kompose down --namespace <given> --force` shall tear down namespace, too.

2a, 2b, just some thoughts. Thanks @kadel for triggering this up.

**Comment by procrypt** [comment]
@kadel Taking this up.
