### ISSUE TITLE
extends is supported construct but conversion doc says opposite

### ISSUE THREAD

**Issue by surajssd** [kubernetes-incubator/kompose#475]
In [conversion doc](https://github.com/kubernetes-incubator/kompose/blob/master/docs/conversion.md) its mentioned that extends is unsupported which is not true.

Not all the forms of doing extends is supported right now but one specific way to do extends from docker-compose is supported in kompose and there is a issue in upstream libcompose to handle that: https://github.com/docker/libcompose/issues/428

**Comment by cdrage** [comment]
You say it's unsupported, but then say that not all forms are supported for libcompose. So at the moment, it is indeed unsupported until https://github.com/docker/libcompose/issues/428 is fixed. I guess we can add that to the conversion doc?

**Comment by surajssd** [comment]
What I mean here is you can still use extends and it works in one form and other one will fail.

**Comment by cdrage** [comment]
So it's still not 100%-supported. I believe we should still say no, but add a note that traditionally Kubernetes a flat-network and everything is interconnected, but when you do `extends` for each Docker container, that functionality will not work and service discovery (such as etcd) is required if you wish to talk for example to the other Docker container via  domain name.

**Comment by kadel** [comment]
As I understand it, only thing that is not working is when you use shorter version (when `extends` is string).
But if you use full format (`extends` is object) than everything is fine.

> So it's still not 100%-supported. I believe we should still say no, but add a note that traditionally Kubernetes a flat-network and everything is interconnected, but when you do extends for each Docker container, that functionality will not work and service discovery (such as etcd) is required if you wish to talk for example to the other Docker container via domain name.

Maybe I missed something, but how can  use of `extends` break service discovery?

**Comment by cdrage** [comment]
@kadel Ah crap, I mixed up `extends` with `external_links`. Ignore my previous comment.

Okay, so implement using `extends` as a string would be the best solution so we have both extends working as an object + string variable

**Comment by kadel** [comment]
> @kadel Ah crap, I mixed up extends with external_links. Ignore my previous comment.

now it makes sense :laughing:


> Okay, so implement using extends as a string would be the best solution so we have both extends working as an object + string variable

that needs to be fixed in  https://github.com/docker/libcompose/issues/428

**Comment by kadel** [comment]
Documentation should say that Kompose supports `extends`

**Comment by cdrage** [comment]
@kadel @surajssd 

Bit confused as to whether this is supported or not, see the below output:

```
▶ cat docker-compose.yaml 
version: '2' 
services:
  foo:
    image: foo 

  bar:
    extends:
      service: foo

~                                                                                                                                                                                                                                                                                
▶ kompose convert --stdout
WARN Unsupported extends key - ignoring   
```

**Comment by kadel** [comment]
yeah :-(

That warning is actually wrong. I've just tested it and it works correctly.

**Comment by kadel** [comment]
https://github.com/kubernetes-incubator/kompose/issues/493
