### ISSUE TITLE
`volumes_from` is supported construct but conversion doc says opposite

### ISSUE THREAD

**Issue by surajssd** [kubernetes-incubator/kompose#476]
In [conversion doc](https://github.com/kubernetes-incubator/kompose/blob/master/docs/conversion.md) its mentioned that `volumes_from` is unsupported which is not true.

So if I mention `volumes_from` in a service then in resulting conversion both the deployments/deploymentconfigs will share same PVC.

**Comment by kadel** [comment]
yep, that is mistake in doc
