### ISSUE TITLE
Add Fedora packaging data to Kompose repo

### ISSUE THREAD

**Issue by cdrage** [kubernetes-incubator/kompose#481]
Move Fedora packaging information (located here: https://github.com/dustymabe/fedpkg-kompose) to the `/build` directory within the root of Kompose. Similar to https://github.com/kubernetes/kubernetes/tree/23cd9d7b05b1ef7ef5073ccc7cbeaf09771c8a43/build

1. It's not that much space to put it in this repo.
2. Keeps everything centralized and simple (can't have another repo on `kubernetes-incubator` called `kompose-packaging`)
3. Keeps everything out in the open for those who want to try packaging it themselves :+1: 

cc @surajssd

**Comment by surajssd** [comment]
Sure it's not just fedora it's rpm in general!
