### ISSUE TITLE
0.4.0 release

### ISSUE THREAD

**Issue by cdrage** [kubernetes-incubator/kompose#501]
Any blockers for this weeks release?

I'll be including a SHA256 hashsum for each binary generated for integrity.

I was thinking of including a signed GPG tarball but according to our previous discussion with @sebgoa and @ngtuna it wasn't feasible to include it since Kubernetes projects don't. A shasum should be enough.

ping @kadel @containscafeine @surajssd @surajnarwade if you have any issues / blockers before the release :)

**Comment by surajnarwade** [comment]
@cdrage , no blockers :)

**Comment by containscafeine** [comment]
@cdrage none from my side :shipit:

**Comment by surajssd** [comment]
@cdrage no blockers from my side!

**Comment by cdrage** [comment]
0.4.0 out! Closing.
