### ISSUE TITLE
kompose fails to build on ppc64 and ppc64le arches due to old sys/unix vendor package

### ISSUE THREAD

**Issue by sinnykumari** [kubernetes-incubator/kompose#532]
Hi,

Kompose-v0.4.0 fails to build on ppc64(le) architectures with following error message:
\# github.com/kubernetes-incubator/kompose/vendor/github.com/fsnotify/fsnotify
src/github.com/kubernetes-incubator/kompose/vendor/github.com/fsnotify/fsnotify/inotify_poller.go:48: undefined: unix.Pipe2

It seems that vendored sys/unix package is old because /vendor/golang.org/x/sys/unix/syscall_linux_ppc64x.go doesn't contain definition of function Pipe2 for ppc64x while upstream has the fixes available https://github.com/golang/sys/commit/b776ec39b3e54652e09028aaaaac9757f4f8211a#diff-ed5775d43461429a9a5247567c3c9fd9R117 .

I built locally and in koji  by replacing /vendor/golang.org/x/sys/unix content with https://github.com/golang/sys/tree/master/unix/ and it builds successfully. 

I tried to update sys package in kompose using "glide get golang.org/x/sys/unix" , didn't use glide up because glide.yaml doesn't have entry for sys/unix . It doesn't seem to go successfully for me, details are at https://paste.fedoraproject.org/paste/nPuAB0vbRIXDwIqyA0YWE15M1UNdIGYhyRLivL9gydE=
. 

Reference
---------------
Complete build log - https://kojipkgs.fedoraproject.org//work/tasks/1264/18671264/build.log
Failed koji build link - https://koji.fedoraproject.org/koji/taskinfo?taskID=18671235
Successful koji build link after sys/unix update - https://koji.fedoraproject.org/koji/taskinfo?taskID=18697032

**Comment by dustymabe** [comment]
ping @kadel @surajssd - this is why we can't get 0.4.0 out into Fedora right now. It looks like we need to update golang.org/x/sys/unix to latest version.

**Comment by cdrage** [comment]
Hey @dustymabe 
I've updated this in #529 

Give it your LGTM and this issue will be fixed :)
