### ISSUE TITLE
Unused functions in app.go and utils.go

### ISSUE THREAD

**Issue by surajnarwade** [kubernetes-incubator/kompose#534]
functions `askForConfirmation` in `app.go`, `TransformData` and `RandStringBytes` in `utils.go` are not called anywhere in kompose, shall we remove them   or they are there for any purpose ?

**Comment by surajssd** [comment]
@surajnarwade yes if that is the case we remove it, do you wanna give it a stab?

**Comment by surajnarwade** [comment]
@surajssd yeah
