### ISSUE TITLE
Update roadmap wrt to k8s 1.7 release

### ISSUE THREAD

**Issue by surajssd** [kubernetes-incubator/kompose#537]
$subject

also needs to be put in https://docs.google.com/document/d/1g5yzEIWoNWJ4tdYRRQP8CE9JSoj4KFemAwayiTE6wnM/edit

**Comment by kadel** [comment]
We don't have to work in sync with Kubernetes releases.
We have our own pace.

But we definitely need roadmap for next few months. 
Its one of the criteria for graduation from incubator.

Lets create our separate roadmap and just link it in that document.

**Comment by kadel** [comment]
done
