### ISSUE TITLE
add documentation about renaming service

### ISSUE THREAD

**Issue by kadel** [kubernetes-incubator/kompose#538]
We should add warning to docs explaining why, when and how we rename service as it may break some docker-compose files

see https://github.com/kubernetes-incubator/kompose/pull/509

**Comment by surajnarwade** [comment]
I will pick this :)

**Comment by procrypt** [comment]
@surajnarwade I'm working on this

**Comment by procrypt** [comment]
Sorry I didn't mentioned it here.

**Comment by surajnarwade** [comment]
@procrypt no issue :)
