### ISSUE TITLE
[UX] Sort output when doing kind: list and --stdout

### ISSUE THREAD

**Issue by dkarlovi** [kubernetes-incubator/kompose#554]
I'm doing some sort of post-processing on the generated YAML to be able to omit `BuildConfig` (as mentioned in #446) etc. When I'm done, I save it to a versioned file to be able to keep track of production config.

When running `kompose convert --provider openshift --verbose --stdout` (which produces a `kind: list`), services' and configuration blocks' order seems to be generated arbitrarily. As this is unimportant for general usage, you might provide a nice UX boost just by sorting the output which would make having it be stable and diffs actually meaningful.

For example, you might go with:
- serviceA, `BuildConfig`
- serviceA, `DeploymentConfig`
- serviceB, `BuildConfig`
- serviceB, `DeploymentConfig`
- etc.

Also, stuff like environment variables and service ports might get sorted by `name`.

**Comment by procrypt** [comment]
@dkarlovi The patten in which the artifacts are generated are intentional since we need the `service` to be created and deployed first as per kubernetes best practices. Although I tried and deployed a sample application in which `service` is deployed after `deploymentConfig` and it works. Can you provide me your `docker-compose` file so that I can try that too.

**Comment by dkarlovi** [comment]
@procrypt I think the whole file gets ingested first, then internally sorted and applied by Kubernetes, which makes sense.

Included are: Compose file and outputs of two consecutive runs of `kompose` (sorry about the long comment).

Here's the `docker-compose.yml` file:

    networks: {}
    services:
      app:
        build:
          context: /src
          dockerfile: ./.infra/docker/php/Dockerfile
        depends_on:
          - broker
          - cache
          - db
        image: dkarlovi/example:app
      broker:
        build:
          context: /src
          dockerfile: ./.infra/docker/rabbitmq/Dockerfile
        hostname: broker
        image: dkarlovi/example:broker
        volumes:
        - broker:/var/lib/rabbitmq:rw
      cache:
        build:
          context: /src
          dockerfile: ./.infra/docker/redis/Dockerfile
        image: dkarlovi/example:cache
        volumes:
        - cache:/data:rw
      db:
        build:
          context: /src
          dockerfile: ./.infra/docker/mysql/Dockerfile
        image: dkarlovi/example:db
        volumes:
        - db:/var/lib/mysql:rw
      web:
        build:
          context: /src
          dockerfile: ./.infra/docker/nginx/Dockerfile
        depends_on:
          - app
          - broker
        image: dkarlovi/example:web
        ports:
        - 80:80/tcp
        - 8000:80/tcp
      worker:
        build:
          context: /src
          dockerfile: ./.infra/docker/worker/Dockerfile
        depends_on:
          - app
          - broker
          - cache
          - db
        image: dkarlovi/example:worker
    version: 2
    volumes:
      broker: {}
      cache: {}
      db: {}

First output of: `kompose -f docker-kompose.yml convert --provider openshift --verbose --build-branch "master" --stdout`:

    apiVersion: v1
    items:
    - apiVersion: v1
      kind: Service
      metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: app
        name: app
      spec:
        clusterIP: None
        ports:
        - name: headless
          port: 55555
          targetPort: 0
        selector:
          io.kompose.service: app
      status:
        loadBalancer: {}
    - apiVersion: v1
      kind: Service
      metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: broker
        name: broker
      spec:
        clusterIP: None
        ports:
        - name: headless
          port: 55555
          targetPort: 0
        selector:
          io.kompose.service: broker
      status:
        loadBalancer: {}
    - apiVersion: v1
      kind: Service
      metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: cache
        name: cache
      spec:
        clusterIP: None
        ports:
        - name: headless
          port: 55555
          targetPort: 0
        selector:
          io.kompose.service: cache
      status:
        loadBalancer: {}
    - apiVersion: v1
      kind: Service
      metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: db
        name: db
      spec:
        clusterIP: None
        ports:
        - name: headless
          port: 55555
          targetPort: 0
        selector:
          io.kompose.service: db
      status:
        loadBalancer: {}
    - apiVersion: v1
      kind: Service
      metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: web
        name: web
      spec:
        ports:
        - name: "80"
          port: 80
          targetPort: 80
        - name: "8000"
          port: 8000
          targetPort: 80
        selector:
          io.kompose.service: web
      status:
        loadBalancer: {}
    - apiVersion: v1
      kind: Service
      metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: worker
        name: worker
      spec:
        clusterIP: None
        ports:
        - name: headless
          port: 55555
          targetPort: 0
        selector:
          io.kompose.service: worker
      status:
        loadBalancer: {}
    - apiVersion: v1
      kind: DeploymentConfig
      metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: app
        name: app
      spec:
        replicas: 1
        selector:
          io.kompose.service: app
        strategy:
          resources: {}
        template:
          metadata:
            creationTimestamp: null
            labels:
              io.kompose.service: app
          spec:
            containers:
            - image: ' '
              name: app
              resources: {}
            restartPolicy: Always
        test: false
        triggers:
        - type: ConfigChange
        - imageChangeParams:
            automatic: true
            containerNames:
            - app
            from:
              kind: ImageStreamTag
              name: app:app
          type: ImageChange
      status: {}
    - apiVersion: v1
      kind: ImageStream
      metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: app
        name: app
      spec: {}
      status:
        dockerImageRepository: ""
    - apiVersion: v1
      kind: BuildConfig
      metadata:
        creationTimestamp: null
        name: app
      spec:
        nodeSelector: null
        output:
          to:
            kind: ImageStreamTag
            name: app:latest
        postCommit: {}
        resources: {}
        runPolicy: Serial
        source:
          contextDir: src
          git:
            ref: master
            uri: git@git.burza.hr:burza/podravka.io.git
          type: Git
        strategy:
          dockerStrategy:
            dockerfilePath: ./.infra/docker/php/Dockerfile
          type: Docker
        triggers:
        - type: ConfigChange
        - type: ImageChange
      status:
        lastVersion: 0
    - apiVersion: v1
      kind: DeploymentConfig
      metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: broker
        name: broker
      spec:
        replicas: 1
        selector:
          io.kompose.service: broker
        strategy:
          resources: {}
          type: Recreate
        template:
          metadata:
            creationTimestamp: null
            labels:
              io.kompose.service: broker
          spec:
            containers:
            - image: ' '
              name: broker
              resources: {}
              volumeMounts:
              - mountPath: /var/lib/rabbitmq
                name: src_broker
            restartPolicy: Always
            volumes:
            - name: src_broker
              persistentVolumeClaim:
                claimName: src_broker
        test: false
        triggers:
        - type: ConfigChange
        - imageChangeParams:
            automatic: true
            containerNames:
            - broker
            from:
              kind: ImageStreamTag
              name: broker:broker
          type: ImageChange
      status: {}
    - apiVersion: v1
      kind: ImageStream
      metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: broker
        name: broker
      spec: {}
      status:
        dockerImageRepository: ""
    - apiVersion: v1
      kind: BuildConfig
      metadata:
        creationTimestamp: null
        name: broker
      spec:
        nodeSelector: null
        output:
          to:
            kind: ImageStreamTag
            name: broker:latest
        postCommit: {}
        resources: {}
        runPolicy: Serial
        source:
          contextDir: src
          git:
            ref: master
            uri: git@git.burza.hr:burza/podravka.io.git
          type: Git
        strategy:
          dockerStrategy:
            dockerfilePath: ./.infra/docker/rabbitmq/Dockerfile
          type: Docker
        triggers:
        - type: ConfigChange
        - type: ImageChange
      status:
        lastVersion: 0
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: src_broker
        name: src_broker
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 100Mi
      status: {}
    - apiVersion: v1
      kind: DeploymentConfig
      metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: cache
        name: cache
      spec:
        replicas: 1
        selector:
          io.kompose.service: cache
        strategy:
          resources: {}
          type: Recreate
        template:
          metadata:
            creationTimestamp: null
            labels:
              io.kompose.service: cache
          spec:
            containers:
            - image: ' '
              name: cache
              resources: {}
              volumeMounts:
              - mountPath: /data
                name: src_cache
            restartPolicy: Always
            volumes:
            - name: src_cache
              persistentVolumeClaim:
                claimName: src_cache
        test: false
        triggers:
        - type: ConfigChange
        - imageChangeParams:
            automatic: true
            containerNames:
            - cache
            from:
              kind: ImageStreamTag
              name: cache:cache
          type: ImageChange
      status: {}
    - apiVersion: v1
      kind: ImageStream
      metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: cache
        name: cache
      spec: {}
      status:
        dockerImageRepository: ""
    - apiVersion: v1
      kind: BuildConfig
      metadata:
        creationTimestamp: null
        name: cache
      spec:
        nodeSelector: null
        output:
          to:
            kind: ImageStreamTag
            name: cache:latest
        postCommit: {}
        resources: {}
        runPolicy: Serial
        source:
          contextDir: src
          git:
            ref: master
            uri: git@git.burza.hr:burza/podravka.io.git
          type: Git
        strategy:
          dockerStrategy:
            dockerfilePath: ./.infra/docker/redis/Dockerfile
          type: Docker
        triggers:
        - type: ConfigChange
        - type: ImageChange
      status:
        lastVersion: 0
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: src_cache
        name: src_cache
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 100Mi
      status: {}
    - apiVersion: v1
      kind: DeploymentConfig
      metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: db
        name: db
      spec:
        replicas: 1
        selector:
          io.kompose.service: db
        strategy:
          resources: {}
          type: Recreate
        template:
          metadata:
            creationTimestamp: null
            labels:
              io.kompose.service: db
          spec:
            containers:
            - image: ' '
              name: db
              resources: {}
              volumeMounts:
              - mountPath: /var/lib/mysql
                name: src_db
            restartPolicy: Always
            volumes:
            - name: src_db
              persistentVolumeClaim:
                claimName: src_db
        test: false
        triggers:
        - type: ConfigChange
        - imageChangeParams:
            automatic: true
            containerNames:
            - db
            from:
              kind: ImageStreamTag
              name: db:db
          type: ImageChange
      status: {}
    - apiVersion: v1
      kind: ImageStream
      metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: db
        name: db
      spec: {}
      status:
        dockerImageRepository: ""
    - apiVersion: v1
      kind: BuildConfig
      metadata:
        creationTimestamp: null
        name: db
      spec:
        nodeSelector: null
        output:
          to:
            kind: ImageStreamTag
            name: db:latest
        postCommit: {}
        resources: {}
        runPolicy: Serial
        source:
          contextDir: src
          git:
            ref: master
            uri: git@git.burza.hr:burza/podravka.io.git
          type: Git
        strategy:
          dockerStrategy:
            dockerfilePath: ./.infra/docker/mysql/Dockerfile
          type: Docker
        triggers:
        - type: ConfigChange
        - type: ImageChange
      status:
        lastVersion: 0
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: src_db
        name: src_db
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 100Mi
      status: {}
    - apiVersion: v1
      kind: DeploymentConfig
      metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: web
        name: web
      spec:
        replicas: 1
        selector:
          io.kompose.service: web
        strategy:
          resources: {}
        template:
          metadata:
            creationTimestamp: null
            labels:
              io.kompose.service: web
          spec:
            containers:
            - image: ' '
              name: web
              ports:
              - containerPort: 80
              - containerPort: 80
              resources: {}
            restartPolicy: Always
        test: false
        triggers:
        - type: ConfigChange
        - imageChangeParams:
            automatic: true
            containerNames:
            - web
            from:
              kind: ImageStreamTag
              name: web:web
          type: ImageChange
      status: {}
    - apiVersion: v1
      kind: ImageStream
      metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: web
        name: web
      spec: {}
      status:
        dockerImageRepository: ""
    - apiVersion: v1
      kind: BuildConfig
      metadata:
        creationTimestamp: null
        name: web
      spec:
        nodeSelector: null
        output:
          to:
            kind: ImageStreamTag
            name: web:latest
        postCommit: {}
        resources: {}
        runPolicy: Serial
        source:
          contextDir: src
          git:
            ref: master
            uri: git@git.burza.hr:burza/podravka.io.git
          type: Git
        strategy:
          dockerStrategy:
            dockerfilePath: ./.infra/docker/nginx/Dockerfile
          type: Docker
        triggers:
        - type: ConfigChange
        - type: ImageChange
      status:
        lastVersion: 0
    - apiVersion: v1
      kind: DeploymentConfig
      metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: worker
        name: worker
      spec:
        replicas: 1
        selector:
          io.kompose.service: worker
        strategy:
          resources: {}
        template:
          metadata:
            creationTimestamp: null
            labels:
              io.kompose.service: worker
          spec:
            containers:
            - image: ' '
              name: worker
              resources: {}
            restartPolicy: Always
        test: false
        triggers:
        - type: ConfigChange
        - imageChangeParams:
            automatic: true
            containerNames:
            - worker
            from:
              kind: ImageStreamTag
              name: worker:worker
          type: ImageChange
      status: {}
    - apiVersion: v1
      kind: ImageStream
      metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: worker
        name: worker
      spec: {}
      status:
        dockerImageRepository: ""
    - apiVersion: v1
      kind: BuildConfig
      metadata:
        creationTimestamp: null
        name: worker
      spec:
        nodeSelector: null
        output:
          to:
            kind: ImageStreamTag
            name: worker:latest
        postCommit: {}
        resources: {}
        runPolicy: Serial
        source:
          contextDir: src
          git:
            ref: master
            uri: git@git.burza.hr:burza/podravka.io.git
          type: Git
        strategy:
          dockerStrategy:
            dockerfilePath: ./.infra/docker/worker/Dockerfile
          type: Docker
        triggers:
        - type: ConfigChange
        - type: ImageChange
      status:
        lastVersion: 0
    kind: List
    metadata: {}
    
Second output of: `kompose -f docker-kompose.yml convert --provider openshift --verbose --build-branch "master" --stdout`:

    apiVersion: v1
    items:
    - apiVersion: v1
      kind: Service
      metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: cache
        name: cache
      spec:
        clusterIP: None
        ports:
        - name: headless
          port: 55555
          targetPort: 0
        selector:
          io.kompose.service: cache
      status:
        loadBalancer: {}
    - apiVersion: v1
      kind: Service
      metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: db
        name: db
      spec:
        clusterIP: None
        ports:
        - name: headless
          port: 55555
          targetPort: 0
        selector:
          io.kompose.service: db
      status:
        loadBalancer: {}
    - apiVersion: v1
      kind: Service
      metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: web
        name: web
      spec:
        ports:
        - name: "80"
          port: 80
          targetPort: 80
        - name: "8000"
          port: 8000
          targetPort: 80
        selector:
          io.kompose.service: web
      status:
        loadBalancer: {}
    - apiVersion: v1
      kind: Service
      metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: worker
        name: worker
      spec:
        clusterIP: None
        ports:
        - name: headless
          port: 55555
          targetPort: 0
        selector:
          io.kompose.service: worker
      status:
        loadBalancer: {}
    - apiVersion: v1
      kind: Service
      metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: app
        name: app
      spec:
        clusterIP: None
        ports:
        - name: headless
          port: 55555
          targetPort: 0
        selector:
          io.kompose.service: app
      status:
        loadBalancer: {}
    - apiVersion: v1
      kind: Service
      metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: broker
        name: broker
      spec:
        clusterIP: None
        ports:
        - name: headless
          port: 55555
          targetPort: 0
        selector:
          io.kompose.service: broker
      status:
        loadBalancer: {}
    - apiVersion: v1
      kind: DeploymentConfig
      metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: cache
        name: cache
      spec:
        replicas: 1
        selector:
          io.kompose.service: cache
        strategy:
          resources: {}
          type: Recreate
        template:
          metadata:
            creationTimestamp: null
            labels:
              io.kompose.service: cache
          spec:
            containers:
            - image: ' '
              name: cache
              resources: {}
              volumeMounts:
              - mountPath: /data
                name: src_cache
            restartPolicy: Always
            volumes:
            - name: src_cache
              persistentVolumeClaim:
                claimName: src_cache
        test: false
        triggers:
        - type: ConfigChange
        - imageChangeParams:
            automatic: true
            containerNames:
            - cache
            from:
              kind: ImageStreamTag
              name: cache:cache
          type: ImageChange
      status: {}
    - apiVersion: v1
      kind: ImageStream
      metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: cache
        name: cache
      spec: {}
      status:
        dockerImageRepository: ""
    - apiVersion: v1
      kind: BuildConfig
      metadata:
        creationTimestamp: null
        name: cache
      spec:
        nodeSelector: null
        output:
          to:
            kind: ImageStreamTag
            name: cache:latest
        postCommit: {}
        resources: {}
        runPolicy: Serial
        source:
          contextDir: src
          git:
            ref: master
            uri: git@git.burza.hr:burza/podravka.io.git
          type: Git
        strategy:
          dockerStrategy:
            dockerfilePath: ./.infra/docker/redis/Dockerfile
          type: Docker
        triggers:
        - type: ConfigChange
        - type: ImageChange
      status:
        lastVersion: 0
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: src_cache
        name: src_cache
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 100Mi
      status: {}
    - apiVersion: v1
      kind: DeploymentConfig
      metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: db
        name: db
      spec:
        replicas: 1
        selector:
          io.kompose.service: db
        strategy:
          resources: {}
          type: Recreate
        template:
          metadata:
            creationTimestamp: null
            labels:
              io.kompose.service: db
          spec:
            containers:
            - image: ' '
              name: db
              resources: {}
              volumeMounts:
              - mountPath: /var/lib/mysql
                name: src_db
            restartPolicy: Always
            volumes:
            - name: src_db
              persistentVolumeClaim:
                claimName: src_db
        test: false
        triggers:
        - type: ConfigChange
        - imageChangeParams:
            automatic: true
            containerNames:
            - db
            from:
              kind: ImageStreamTag
              name: db:db
          type: ImageChange
      status: {}
    - apiVersion: v1
      kind: ImageStream
      metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: db
        name: db
      spec: {}
      status:
        dockerImageRepository: ""
    - apiVersion: v1
      kind: BuildConfig
      metadata:
        creationTimestamp: null
        name: db
      spec:
        nodeSelector: null
        output:
          to:
            kind: ImageStreamTag
            name: db:latest
        postCommit: {}
        resources: {}
        runPolicy: Serial
        source:
          contextDir: src
          git:
            ref: master
            uri: git@git.burza.hr:burza/podravka.io.git
          type: Git
        strategy:
          dockerStrategy:
            dockerfilePath: ./.infra/docker/mysql/Dockerfile
          type: Docker
        triggers:
        - type: ConfigChange
        - type: ImageChange
      status:
        lastVersion: 0
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: src_db
        name: src_db
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 100Mi
      status: {}
    - apiVersion: v1
      kind: DeploymentConfig
      metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: web
        name: web
      spec:
        replicas: 1
        selector:
          io.kompose.service: web
        strategy:
          resources: {}
        template:
          metadata:
            creationTimestamp: null
            labels:
              io.kompose.service: web
          spec:
            containers:
            - image: ' '
              name: web
              ports:
              - containerPort: 80
              - containerPort: 80
              resources: {}
            restartPolicy: Always
        test: false
        triggers:
        - type: ConfigChange
        - imageChangeParams:
            automatic: true
            containerNames:
            - web
            from:
              kind: ImageStreamTag
              name: web:web
          type: ImageChange
      status: {}
    - apiVersion: v1
      kind: ImageStream
      metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: web
        name: web
      spec: {}
      status:
        dockerImageRepository: ""
    - apiVersion: v1
      kind: BuildConfig
      metadata:
        creationTimestamp: null
        name: web
      spec:
        nodeSelector: null
        output:
          to:
            kind: ImageStreamTag
            name: web:latest
        postCommit: {}
        resources: {}
        runPolicy: Serial
        source:
          contextDir: src
          git:
            ref: master
            uri: git@git.burza.hr:burza/podravka.io.git
          type: Git
        strategy:
          dockerStrategy:
            dockerfilePath: ./.infra/docker/nginx/Dockerfile
          type: Docker
        triggers:
        - type: ConfigChange
        - type: ImageChange
      status:
        lastVersion: 0
    - apiVersion: v1
      kind: DeploymentConfig
      metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: worker
        name: worker
      spec:
        replicas: 1
        selector:
          io.kompose.service: worker
        strategy:
          resources: {}
        template:
          metadata:
            creationTimestamp: null
            labels:
              io.kompose.service: worker
          spec:
            containers:
            - image: ' '
              name: worker
              resources: {}
            restartPolicy: Always
        test: false
        triggers:
        - type: ConfigChange
        - imageChangeParams:
            automatic: true
            containerNames:
            - worker
            from:
              kind: ImageStreamTag
              name: worker:worker
          type: ImageChange
      status: {}
    - apiVersion: v1
      kind: ImageStream
      metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: worker
        name: worker
      spec: {}
      status:
        dockerImageRepository: ""
    - apiVersion: v1
      kind: BuildConfig
      metadata:
        creationTimestamp: null
        name: worker
      spec:
        nodeSelector: null
        output:
          to:
            kind: ImageStreamTag
            name: worker:latest
        postCommit: {}
        resources: {}
        runPolicy: Serial
        source:
          contextDir: src
          git:
            ref: master
            uri: git@git.burza.hr:burza/podravka.io.git
          type: Git
        strategy:
          dockerStrategy:
            dockerfilePath: ./.infra/docker/worker/Dockerfile
          type: Docker
        triggers:
        - type: ConfigChange
        - type: ImageChange
      status:
        lastVersion: 0
    - apiVersion: v1
      kind: DeploymentConfig
      metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: app
        name: app
      spec:
        replicas: 1
        selector:
          io.kompose.service: app
        strategy:
          resources: {}
        template:
          metadata:
            creationTimestamp: null
            labels:
              io.kompose.service: app
          spec:
            containers:
            - image: ' '
              name: app
              resources: {}
            restartPolicy: Always
        test: false
        triggers:
        - type: ConfigChange
        - imageChangeParams:
            automatic: true
            containerNames:
            - app
            from:
              kind: ImageStreamTag
              name: app:app
          type: ImageChange
      status: {}
    - apiVersion: v1
      kind: ImageStream
      metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: app
        name: app
      spec: {}
      status:
        dockerImageRepository: ""
    - apiVersion: v1
      kind: BuildConfig
      metadata:
        creationTimestamp: null
        name: app
      spec:
        nodeSelector: null
        output:
          to:
            kind: ImageStreamTag
            name: app:latest
        postCommit: {}
        resources: {}
        runPolicy: Serial
        source:
          contextDir: src
          git:
            ref: master
            uri: git@git.burza.hr:burza/podravka.io.git
          type: Git
        strategy:
          dockerStrategy:
            dockerfilePath: ./.infra/docker/php/Dockerfile
          type: Docker
        triggers:
        - type: ConfigChange
        - type: ImageChange
      status:
        lastVersion: 0
    - apiVersion: v1
      kind: DeploymentConfig
      metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: broker
        name: broker
      spec:
        replicas: 1
        selector:
          io.kompose.service: broker
        strategy:
          resources: {}
          type: Recreate
        template:
          metadata:
            creationTimestamp: null
            labels:
              io.kompose.service: broker
          spec:
            containers:
            - image: ' '
              name: broker
              resources: {}
              volumeMounts:
              - mountPath: /var/lib/rabbitmq
                name: src_broker
            restartPolicy: Always
            volumes:
            - name: src_broker
              persistentVolumeClaim:
                claimName: src_broker
        test: false
        triggers:
        - type: ConfigChange
        - imageChangeParams:
            automatic: true
            containerNames:
            - broker
            from:
              kind: ImageStreamTag
              name: broker:broker
          type: ImageChange
      status: {}
    - apiVersion: v1
      kind: ImageStream
      metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: broker
        name: broker
      spec: {}
      status:
        dockerImageRepository: ""
    - apiVersion: v1
      kind: BuildConfig
      metadata:
        creationTimestamp: null
        name: broker
      spec:
        nodeSelector: null
        output:
          to:
            kind: ImageStreamTag
            name: broker:latest
        postCommit: {}
        resources: {}
        runPolicy: Serial
        source:
          contextDir: src
          git:
            ref: master
            uri: git@git.burza.hr:burza/podravka.io.git
          type: Git
        strategy:
          dockerStrategy:
            dockerfilePath: ./.infra/docker/rabbitmq/Dockerfile
          type: Docker
        triggers:
        - type: ConfigChange
        - type: ImageChange
      status:
        lastVersion: 0
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: src_broker
        name: src_broker
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 100Mi
      status: {}
    kind: List
    metadata: {}

**Comment by surajssd** [comment]
@dkarlovi so this was intentional as @procrypt said also you can find the corresponding doc in upstream at 
https://kubernetes.io/docs/concepts/configuration/overview/

which says:

>It’s typically best to create a service before corresponding replication controllers, so that the scheduler can spread the pods comprising the service. 

so the decision.

**Comment by dkarlovi** [comment]
@surajssd thanks for the link. I've noted:
> It doesn't matter WHAT the actual sort is as long as it's repeatable and stable.

As you can see from my comment, order changes between runs for me.

**Comment by surajssd** [comment]
@dkarlovi thanks for reporting this seems to be an openshift issue!

**Comment by surajssd** [comment]
With Kubernetes the output is right but with openshift the output is not alphabetically ordered

**Comment by dkarlovi** [comment]
@surajssd great to hear. Sorting by docker-compose works too of course, as long as the order is kept between runs.

**Comment by procrypt** [comment]
@surajssd @dkarlovi I have updated the [PR](https://github.com/kubernetes-incubator/kompose/pull/565) accordingly, output with is in order `OpenShift` now.
