### ISSUE TITLE
0.6.0 Release

### ISSUE THREAD

**Issue by cdrage** [kubernetes-incubator/kompose#574]
Let's merge these two before release:
 - https://github.com/kubernetes-incubator/kompose/pull/454
 - https://github.com/kubernetes-incubator/kompose/pull/557

**Comment by ngtuna** [comment]
https://github.com/kubernetes-incubator/kompose/pull/557 has been merged.

**Comment by cdrage** [comment]
and so has #454 let's do a release!

**Comment by surajssd** [comment]
closing since https://github.com/kubernetes-incubator/kompose/pull/582 is merged
