### ISSUE TITLE
Failing test should show diff

### ISSUE THREAD

**Issue by kadel** [kubernetes-incubator/kompose#604]
If one test in  `make test-cmd` fails it just shows following message:
```
FAIL: converted output does not match
```

It is quite annoying to debug why this test is failing because you have to run it again manually to catch output and do `diff` with the expected output.

Diff should be shown automatically for.

**Comment by cdrage** [comment]
I totally agree. It's annoying to not know what's exactly wrong between the two :-1:

**Comment by surajnarwade** [comment]
taking this up :)

**Comment by surajnarwade** [comment]
@cdrage @kadel we can close this as #638 is merged now
