### ISSUE TITLE
Add support for 'pid' key

### ISSUE THREAD

**Issue by gitlawr** [kubernetes-incubator/kompose#610]
In compose file, [pid](https://docs.docker.com/compose/compose-file/#pid) key is merely used to set the PID mode to the host PID mode (and no support for pid=container:id). Therefore I think it can be converted to [Pod.Spec.HostPid](https://kubernetes.io/docs/resources-reference/v1.6/#podspec-v1-core) in K8s.

**Comment by surajnarwade** [comment]
@gitlawr , but k8s spec is boolean here

**Comment by gitlawr** [comment]
yes, but it seems to be the same in compose file, you choose pid='host' or not

**Comment by surajnarwade** [comment]
@surajssd @kadel thoughts ?

**Comment by cdrage** [comment]
It should be fine.. `if pid=="host` make the boolean true in k8s...
