### ISSUE TITLE
configuration key 'build' contains an invalid type, it should be a string.

### ISSUE THREAD

**Issue by verisadmin** [kubernetes-incubator/kompose#620]
- I have docker-compose file whixh extends other compose files and setup my apps. It is working fine.
- But When I tried same file with `kompose` I am getting invalid type error : 

```
ERRO Failed to parse service micro_service_api: Service 'v_test' configuration key 'build' contains an invalid type, it should be a string. 
```

- here are my Compose files : 
   - Main : 

```
version: '2'

services:
  test_micro_service_api:
    extends :
      file : ../v-test/docker-compose-test.yml
      service : v_test
```

   - child : 

```
version: "2"

services:
  v_test:
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
     - ../locale/env/test_service
    environment:
     DEBUG: 'true'
    command: bash -c "python ./manage.py migrate && python ./manage.py runserver 0.0.0.0:8018"
    volumes:
     - .:/v-test
    ports:
     - "8018:8018"
```

**Comment by surajssd** [comment]
@verisadmin what is the version of kompose you are using?

**Comment by verisadmin** [comment]
@surajssd  
`0.7.0 (c25b7e8)`

**Comment by kadel** [comment]
this looks like bug in libcompose :-( 
It seems like for some reason extends and with builds are not handled properly :(

**Comment by surajnarwade** [comment]
I will take this up

**Comment by surajnarwade** [comment]
I have filed issue in libcompose which can be tracked here: https://github.com/docker/libcompose/issues/475
