### ISSUE TITLE
ports error on converting

### ISSUE THREAD

**Issue by changux** [kubernetes-incubator/kompose#633]
Hi.

I am trying to convert this docker-compose file:

[https://raw.githubusercontent.com/wazuh/wazuh-docker/master/docker-compose.yml]()

With this output:

```bash
ERRO Could not parse config for project kompose : Service 'wazuh' configuration key 0 value Does not match format 'ports'
Service 'wazuh' configuration key 2 value Does not match format 'ports'
FATA composeObject.Parse() failed, Failed to load compose file: Service 'wazuh' configuration key 0 value Does not match format 'ports'
Service 'wazuh' configuration key 2 value Does not match format 'ports'
```
Docker-compose file is valid, what is wrong?

Thanks!

**Comment by cdrage** [comment]
@changux 

Try: 
```
      - "514:514/udp"
```

instead of

```
      - "514/udp:514/udp"
```

and see what happens.

**Comment by kadel** [comment]
hmm, interesting. It looks like "514/udp:514/udp" is supported by docker-compose tool, but not by libcompose.

It's strange as I don't see why it would ever make sense to set different protocol for container and host port.

**Comment by changux** [comment]
Thanks. After follow your suggestions, convert process finished successfully.

Regards!
