### ISSUE TITLE
We should have a table / document for docker-compose to k8s / openshift conversion  

### ISSUE THREAD

**Issue by janetkuo** [kubernetes-incubator/kompose#82]
It'll be helpful for developers and users to have such docs.

**Comment by janetkuo** [comment]
We can probably auto-generate this.

**Comment by pradeepto** [comment]
@janetkuo You should talk to @kadel I remember him doing something similar for henge.

**Comment by ngtuna** [comment]
so @kadel can you help ?

**Comment by kadel** [comment]
I started this for Henge, but I just had rough draft, you can see it in Henge's wiki https://github.com/redhat-developer/henge/wiki/Mappings We also had some internal document describing this with more details. I will try to find it and see if we can use that.

I really like @janetkuo idea of auto-generating this. How would you like to do that?

**Comment by janetkuo** [comment]
I'm thinking that we can use yaml tags of each field of different struct (libcompose, kobject, and kubernetes objects) and create `map[string]string` that maps one yaml tag to another (e.g. libcompose ServiceConfig's `image` maps to kobject's `image` which maps to k8s Container `image`). We can use that in code for conversion as well as auto-generate the table by printing the map. WDYT?

**Comment by kadel** [comment]
I never thought about using tags like this. It sounds cool.

**Comment by surajnarwade** [comment]
@kadel as we have conversion table at http://kompose.io/conversion/, we can close this issue.

**Comment by cdrage** [comment]
@surajnarwade :+1: Closin'
